### ISSUE TITLE
FF4J 2.0

### ISSUE THREAD

**Issue by clun** [ff4j/ff4j#172]
The team has started to work on v2 with - again - a lot of Features
- Support of Java8+ (heavy refactoring)
- Split AuditTrail (audit logs) and FeatureUsageTracking
- Introducing Permissions and ACL
- Angular4 console based
- New Stores (AWS RDS, Eureka)

We expect to release a RC1 in late Q1 2017.

**Comment by kutzi** [comment]
Sounds great.
Any rough ETA on this?

**Comment by clun** [comment]
Hard to estimate. 

On branch 2.x the ff4j-core has been refactored. Current implementing the Jdbc store to see if everything is good. (feedback are welcomed). I expected to have a RC1 at end of Q1.

![ff4j-v2](https://cloud.githubusercontent.com/assets/726536/21752507/c4bcb586-d5d9-11e6-96a5-738923838e6b.png)

XML Definition become

![ff4j-v2-xml](https://cloud.githubusercontent.com/assets/726536/21752508/c8abe734-d5d9-11e6-9398-d7732799f200.png)

**Comment by cula** [comment]
Hi,
I cannot find anything like FeatureMongoStore in the `org.ff4j.store`. Does it mean this feature has not been supported? And will this feature being supported in 2.0? 
Ps: there is only a title in the doc to tell readers that mongo is supported but i found nothing...

**Comment by clun** [comment]
Hello, The version 2.0 is far for ready. It does not compile for instance.... Only ff4j-core has evolutions and unfortunately I am out of time at the moment, contribution would be welcome. 

Don't worry there will be support for Mongo as both creator or Fongo and MongoBee are contributor to this lib. So far we cannot progress, no time.... priority on 1.7 and community.

**Comment by cula** [comment]
thx.
However, I'm afraid I have to write a mongo store myself first because FF4J is used as an independent sever to offer feature toggle service for other service in my case. So the storage should be persistent and remote. 
So far it's based on MongoDB-driver only. I'll look into fongo and mongoBee as well. Hope this will help.

**Comment by clun** [comment]
Well, then I am confused. We already have 3 stores for Mongo (V2 and V3) in 1.7. You can easily 

1. Create a StandAlone APP (using Spring boot starter ff4j) 
2. Setup store to use a mongoDB instance somewhere
3. Setup other application to use the REST API as clients and do not have direct link to DB

Do you need something else ? You can have a look #245

**Comment by cula** [comment]
Sorry, I've no idea when version 1.7 will be released. So I write one based on version 1.5.  Now I'm working on updating my code to "ff4j-store-mongodb-v3". Thank u very much~

**Comment by clun** [comment]
Not relevant with further developments would recreate dedicated small issues
