### ISSUE TITLE
Thymeleaf 3

### ISSUE THREAD

**Issue by danielswars** [ff4j/ff4j#186]
Is there any plan for having a Thymeleaf 3 integration? We are currently migrate from Thymeleaf 2 to Thymeleaf 3 but the ff4j-web module is only working for Thymeleaf 2.

**Comment by clun** [comment]
Hi,

I understand the issue, that this is one of the limit of an embedded servlet (dragging some dependencies not compatible with the host application...). 

Thymeleaf 3 is out for 8 months now, we didn't notice this release. We are not *against* moving to thymeleaf 3, it make sense. Yet It is not easy to estimate the migration effort.

I can suggest 3 things.: 
- I let the issue opened and include it as soon as I can, maybe 1.7.x as it's a broken change. Il will definitively be part of 2.x in progress on dedidacted branch. We can expect to be ready for june.

- You can have look here where all thymeleaf stuff are [here](https://github.com/clun/ff4j/tree/master/ff4j-web/src/main/java/org/ff4j/web/controller), [here](https://github.com/clun/ff4j/tree/master/ff4j-web/src/main/java/org/ff4j/web/thymeleaf) and [here](https://github.com/clun/ff4j/tree/master/ff4j-web/src/main/resources/views). As you are in the middle of process of migration you may easily change this few classes and propose a PR

- You may consider to create a small dedicated backend administration application hosting the  ff4j servlet, to decoupled from other applications. This application will point on the same FeatureStores are your applications (Databases, not in-memory).

Enjoy!

**Comment by danielswars** [comment]
Hi,
thx for the comprehensive  answer. :)
I made a branch where I added the thymeleaf 3 dependencies and migrated the thymeleaf classes so that I can deploy a different ff4j-web module.
This branch contains only a few straight-forward changes as you can see [here](https://github.com/eSailors/ff4j/tree/thymeleaf_3_integration).

This will work for us by now but I don't think this is the kind of integration you want to have for everyone.
On the midterm it makes maybe sense to have a submodule for a thymleaf 2 integration and a submodule for the thymleaf 3 integration so that the user can decide what he wants to use since thymeleaf 2 is still pretty common.

**Comment by clun** [comment]
We are using the Thymeleaf3 for some time now, specially with the spring boot starter
