### ISSUE TITLE
Recommended configuration for AWS

### ISSUE THREAD

**Issue by efenderbosch** [ff4j/ff4j#240]
I'm thinking that a RDS PostgreSQL data store with ElastiCache (Memcached) cache might work well.

Use would be from various AWS Lambdas that use Google Guice for DI. I see many of the examples use Spring. Is using Guice supported w/ aop/dynamic proxies?

**Comment by clun** [comment]
AWS is indeed a great path to improve for ff4j.

Todo list:
- [ ]  Allow dynamic proxies with CGLIB and not only SpringAOP and allow Guice DI
- [x] Create ff4j-store-aws-rds working with PostGresSQL
- [ ] Create ff4j-store-aws-elasticache

Questions : 
Can RDS simply work with a JDBC URL and driver ?

**Comment by efenderbosch** [comment]
Yes, we should be able to use simple JDBC properties to connect to RDS.

Is there a manual workaround for now for the dynamic proxies w/ Guice?

**Comment by efenderbosch** [comment]
Something like this might be a decent start:

```java
public class FF4JModule extends AbstractModule {

    @Override
    protected void configure() {
        Matcher classMatcher = Matchers.any();
        Matcher methodMatcher = Matchers.annotatedWith(Flip.class);
        bindInterceptor(classMatcher, methodMatcher, new FF4JMethodInterceptor());
    }

    public static class FF4JMethodInterceptor implements MethodInterceptor {
        @Override
        public Object invoke(MethodInvocation invocation) throws Throwable {
            // TODO ff4j stuff
            return null;
        }
    }
}
```

I'm not sure if ``Matchers::annotatedWith`` will chase up the object hierarchy, though.

**Comment by clun** [comment]
Dynamic proxy will leverage on CGLIB in V2 but no specific support for Google Guice

Note that lot of stores works with AWS now : RDS, Aurora (JDBC), ElasticCache, Mongo/DocumentDB, SSM
