### ISSUE TITLE
FeatureAutoProxy should scan interfaces on superclasses in addition to the given class (?)

### ISSUE THREAD

**Issue by lucjross** [ff4j/ff4j#248]
https://github.com/clun/ff4j/blob/master/ff4j-aop/src/main/java/org/ff4j/aop/FeatureAutoProxy.java#L59

That line will get the interfaces directly implemented by the class, but not those implemented by any superclasses--for example, interfaces implemented by an abstract class that implements some non-flippable methods common to the two flippable implementations. And if the abstract class implements the interface then logically the subclasses do as well. If you agree, I would be happy to contribute an update. And thank you for the AOP stuff, it'll do wonders for minimizing technical debt from our feature toggles!

**Comment by clun** [comment]
Thank ou for you kind words :) I do agree with your idea, please go ahead and contribute / always good to have people involve. 

AOP is indeed useful but there is a drawback in current implementation : it's based on Spring AOP where I could simply use CGLIB and dynamic proxies, i expect to change that for 2.x.

I notice you contribute to MongoBee as well good !! Will need it soon in the JHipster FF4J generator. Today I made the files for Liquibase but not MongoBee.

If you interested in contributing I would be able to give ou a license of IntelliJ Ultimate thanks to the support of JetBrains.

Regards

**Comment by clun** [comment]
I am afraid I will close this one, to focus on v2 with pure `cglib`.
