### ISSUE TITLE
Support Spring RedisTemplate in FeatureStoreRedis

### ISSUE THREAD

**Issue by kutzi** [ff4j/ff4j#258]
I would be nice if the would be an option to use the FeatureStoreRedis with Spring's RedisTemplate.

Currently we have our own custom FeatureStore implementation based on StringRedisTemplate mostly for that reason.
A nice side effect of that is that RedisTemplate does transparently support using cluster, sentinel or 'plain' Redis mode with only changing some configuration keys.

**Comment by kutzi** [comment]
Maybe it's possble to capsule this somehow in RedisConnection. To keep the core free of spring dependencies you could put the custom RedisConnection into ff4j-spring-boot-autoconfigure

**Comment by paul58914080** [comment]
I'll see what I can do about this

**Comment by clun** [comment]
Caution Paul.. Kutzi is brilliant but demanding (always justified though)  :)

**Comment by clun** [comment]
Here we are back - I know 3 years later. 

- I am not convinced about this `RedisConnection` wrapper anymore but we should not introduce breaking changes.

- Both SpringRedisTemplate (now spring-data-redis) and `ff4j` use Jedis. We should define the bean once and inject.

Spring
```java
@Bean
    public JedisConnectionFactory redisConnectionFactory() {
        JedisConnectionFactory jedisConnectionFactory = new JedisConnectionFactory();
        jedisConnectionFactory.setHostName("your_host_name_or_ip");
        jedisConnectionFactory.setPort(6379);
        jedisConnectionFactory.afterPropertiesSet();
        return jedisConnectionFactory;
    }
```

We could create an additional contructor in `RedisConnection` to avoid breaking change. Best would be probably to have the JedisConnectionFactory part of the FF4jStore object directly as well.

**Comment by clun** [comment]
Please do with SpringBoot 2x+

```java
@Bean
public JedisPool getJedisPool(RedisProperties redisProperties) {
    Pool jedisProperties = redisProperties.getJedis().getPool();
    String password = StringUtils.isEmpty(redisProperties.getPassword()) ? null : redisProperties.getPassword();
    int timeout = (int) redisProperties.getTimeout().toMillis();
    
    GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
    poolConfig.setMaxIdle(jedisProperties.getMaxIdle());
    poolConfig.setMaxTotal(jedisProperties.getMaxActive() + jedisProperties.getMaxIdle());
    poolConfig.setMinIdle(jedisProperties.getMinIdle());
    log.info("Starting Redis with Host:{}, Port:{}, Timeout(ms):{}, PoolConfig:{}", redisProperties.getHost(), redisProperties.getPort(),
            timeout, poolConfig);
    return new JedisPool(poolConfig, redisProperties.getHost(), redisProperties.getPort(), timeout, password);
}

@Bean
public RedisConnection(JedisPool pool) {
  return new RedisConnection(pool);
}

...
```
