### ISSUE TITLE
FF4J Groups and Permissions not displaying in the console

### ISSUE THREAD

**Issue by abuinteam** [ff4j/ff4j#277]
Hello Team,

Thanks for the wonderful contribution on the FF4J. I am looking into the permissions and groups to enable features only certain list of people. I want to use our existing Active Directory groups in our features since our applications are legacy and we are not using Spring Security nor Apache Shiro.

I am using FF4J in such a way that, FF4J admin console was installed in seperate server and all our applications are connecting to admin console using a REST API using FeatureStoreHttp.

In the admin console application, I have added a custom authorization manager class which I have implemented like below.

public class FeatureAuthorizationManager implements AuthorizationsManager {

	@Override
	public String getCurrentUserName() {
		// TODO Auto-generated method stub
		return "mabuthahir@123.com";
	}

	@Override
	public Set<String> getCurrentUserPermissions() {
		// TODO Auto-generated method stub
		final Set<String> permissions = new HashSet<>();
		permissions.add("Admin");
		permissions.add("User");
		return permissions;
	}

	@Override
	public Set<String> listAllPermissions() {
		final Set<String> permissions = new HashSet<>();
		permissions.add("Admin");
		permissions.add("User");
		return permissions;
	}

	@Override
	public String toJson() {
		// TODO Auto-generated method stub
		return null;
	}

}

**Questions**

1. As per the documentation, the permissions are returned from listAllPermissions which should display in admin console. But right now it is not displaying. My idea is inside the  listAllPermissions method I will write a logic to read groups from Active Directory.

The below is my ff4j configuration for my admin console application,

final AuthorizationsManager authorizationsManager = new FeatureAuthorizationManager();
    	 FF4j ff4j = new FF4j();
         FF4JCacheManager ff4jCacheManager = new FeatureCacheProviderEhCache();
         ff4j.setFeatureStore(new FeatureStoreSpringJdbc(dataSource));
         ff4j.setPropertiesStore(new PropertyStoreSpringJdbc(dataSource));
         ff4j.setEventRepository(new EventRepositorySpringJdbc(dataSource));
         ff4j.autoCreate(true);
         ff4j.audit(true);
         ff4j.cache(ff4jCacheManager);
         ff4j.createSchema();
         ff4j.setAuthorizationsManager(authorizationsManager);
         return ff4j;

2. What is the **Group** dropdown displaying in admin console. What is the purpose of it? Difference between group and permissions?

3. How can I send the current user name from my client application to server application (my application to rest api)

At the client I am using the ff4j setup like this,

ff4j = new FF4j();
ff4j.setFeatureStore(new FeatureStoreHttp("http://*****:9082/api/ff4j"));
ff4j.setPropertiesStore(new PropertyStoreHttp("http://****:9082/api/ff4j"));
ff4j.autoCreate(true);
ff4j.audit(true);	        
servletContext.setAttribute(FF4JConstant.FF4J, ff4j);

This is a singleton instance which will be instantiated only once during server start up. In this case how can I send user id or email id to the server?

**Comment by abuinteam** [comment]
**I feel Group is to group certain features together. I got confused with security groups.** I got it now.

**Comment by abuinteam** [comment]
Looks like FeatureAuthorizationManager  I should implement in my client side (in my application side) and not at the server console side. Please correct me if my understanding is correct.

**Comment by clun** [comment]
*I am using FF4J in such a way that, FF4J admin console was installed in seperate server and all our applications are connecting to admin console using a REST API using FeatureStoreHttp.*

**This is indeed, for me, the best pattern. All your application can set up the `FeatureStoreHttp` but also cacheProxy in order to avoid REST call each time which may introduce some overhead. You can have a look here https://github.com/clun/ff4j/wiki/Advanced-Concepts#caching.**

*(1) As per the documentation, the permissions are returned from listAllPermissions which should display in admin console. But right now it is not displaying. My idea is inside the listAllPermissions method I will write a logic to read groups from Active Directory.*

**The `listAllPermissions` is used to display the combobox in the admin console UI. It is the indeed the place to query LDAP and fetch groups.**

Not finished answering...

**Comment by abuinteam** [comment]
Hello Clun,

Thank you for getting back on this. Yes I am using the caching on the admin console application. I hope thats the correct place to implement and not on my client side. 

As per the code that have shared above, I hard coded some values in the listAllPermissions and I expected to see in the admin console which is missing. I am waiting for your answer :)

**Comment by abuinteam** [comment]
Hello Clun,

Any update on this?

**Comment by kevinwenzhang** [comment]
Hi @abuinteam @clun, I'm wondering the same. Was there a resolution to this question?

**Comment by abuinteam** [comment]
Hi @kevinwenzhang  Unfortunately not succeeded on this.

**Comment by sayantansinha** [comment]
I just posted a similar question, hoping there would be some answer. I am totally confused as to how this would work, especially, how the feature flag server would be aware of the user context  while checking access.

**Comment by clun** [comment]
1.  Create an `AuthorizationsManager` like [here](https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/test/java/org/ff4j/test/DefinedPermissionSecurityManager.java) leveraging on an existing security framework
2. Security can be Spring Security or Shiro in both cas you will read in the SecurityContext. This is most of the time a ThreadLocal. FF4j read from the security context of the Application and does not create one.

I will close this one as duplication of #393. I am working on a sample to 
- Secure the application (Spring Security) login/password
- Secure access to the web-console (only admin role can access)
- Toggle feature leveraging the context
