### ISSUE TITLE
FF4j Console Application - Deploy in Apache Tomcat

### ISSUE THREAD

**Issue by abuinteam** [ff4j/ff4j#278]
Hi Team,

I am trying to deploy the **ff4j-sample-springboot-jdbc** admin console application into Apache Tomcat. I have made the packaging type as war and removed the embedded tomcat from Spring Boot. But i could not able to deploy into Tomcat. I am using Tomcat 8.5. Is there any steps to do deploy into Tomcat?

**Comment by clun** [comment]
Well, "spring-boot" means indeed standAlone applications and not hosted in Tomcat server application. 
To deploy in Tomcat please create a webApplication (with WEB-INF/web.xml). 

Here is a sample :https://github.com/clun/ff4j-samples/tree/master/ff4j-sample-web

**Comment by abuinteam** [comment]
Yes but Spring Boot provides a way to deploy the app as WAR in our own custom server instead of embedded tomcat. I have done that in the past for my other Spring Boot application. Let me check on this further and if I have the updates I will keep posted in this thread.

**Comment by clun** [comment]
Any update here ? I may close this one.

**Comment by abuinteam** [comment]
I have not gone the route of "war". Packaged as Jar and running as a windows service using embedded tomcat. So this can be closed for now.
