### ISSUE TITLE
Audit issue with 1.7 on checkOn events

### ISSUE THREAD

**Issue by clun** [ff4j/ff4j#279]
checkOn event is not getting inserted when I access the feature from JSP or Java Class. This was working fine in 1.6.5. Since the event was not loading graphs are not working. Would be great if this is fixed.

**Comment by abuinteam** [comment]
Hi Clun,

Will this issue be fixed in the next release?

**Comment by abuinteam** [comment]
Checking to see whether this will be fixed?

**Comment by clun** [comment]
This is totally fixed for a while : working sample https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-springboot2x
