### ISSUE TITLE
Add new feature from admin console. shows error

### ISSUE THREAD

**Issue by suchins3** [ff4j/ff4j#287]
When i add new feature from admin console. shows below error and post is not  working 

java.lang.IllegalStateException: ServletConfig has not been initialized
	javax.servlet.GenericServlet.getServletContext(GenericServlet.java:199)
	org.ff4j.web.embedded.ConsoleServlet.doPost(ConsoleServlet.java:370)

**Comment by clun** [comment]
Hi,

No lot of details here. Seems your are using a version before 1.6. (as using old class ConsoleServlet). 
https://github.com/clun/ff4j/blob/master/ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleServlet.java#L369-L371

It's like you do not provide FF4J to the servlet. Here is the way to declare the servlet : https://github.com/clun/ff4j/wiki/Web-Concepts#web-console

+ If you are using a version > 1.6 please use the Dispatcher servlet, the one that evolve.

You have a simple working solution here : 
https://github.com/clun/ff4j-samples

**Comment by suchins3** [comment]
Thanks for the update,
I am using version 1.7 and servlet also has been defined,
Will try **Dispatcher servlet** and update

Thanks,

**Comment by clun** [comment]
Did you manage to implement what you need ?

**Comment by suchins3** [comment]
Yes, Thanks :-)
