### ISSUE TITLE
Admin Console with Spanish Language Support

### ISSUE THREAD

**Issue by garrablanca** [ff4j/ff4j#288]
## It would be great to update the support for the Spanish Language in the FF4J Admin Console

**NOTE:**
Actually I already have added and fixed in my local environment to support it,  this files:
 
-  flagMexico.png
-   view-navbar.html
- ff4j-messages_es.properties

if you allow me to do a Pull request, I'll submit this new files.

Regards

**Comment by clun** [comment]
Yes !! Thank you, of course any PR is welcomed and hopefully quickly merged :)

**Comment by garrablanca** [comment]
Oh thanks, well the Pull Request is started...
  
Pull Request: https://github.com/clun/ff4j/pull/290

Regards

**Comment by garrablanca** [comment]
Ok, this issue was solved and is already merged into the code, can we close this one ?
Thanks
