### ISSUE TITLE
FF4J Admin Console, ' Edit a Feature' window

### ISSUE THREAD

**Issue by garrablanca** [ff4j/ff4j#289]
# Dynamic Selection Box (drop down) for Used Strategies on Edit a Feature Window
For now, there is no dynamic catalog for the strategies classes, it only shows those that are fixed in the view-model-features.html file.

One idea is that, in addition to the fixed section of strategies, it would be good to dynamically present one of each new classes defined in the saved features, then it would be easier to select a strategy for a new or current configuration of a feature.

Regards

**Comment by clun** [comment]
Nice idea ! Could also be the occasion to scan the classpath to fetch for implementation of  [FlippingStrategy](https://github.com/clun/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/core/FlippingStrategy.java) and would be a method of `getAvailableFlippingStrategies()` at [FeatureStore](https://github.com/clun/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/core/FeatureStore.java)

**Comment by garrablanca** [comment]
Ok, this issue was solved and it's already merged into the code.
Thanks
