### ISSUE TITLE
FF4J @Flip annotation not intercepted and FeatureAdvisor.invoke not triggered

### ISSUE THREAD

**Issue by anthonyrichir** [ff4j/ff4j#292]
I'm trying to set FF4J on a Jhipster project via the module from the marketplace, I updated the generated dependencies to version 1.7.1.
My goal is to flip between 2 implementations of a service interface used by a resource.

Here is the interface of the service:

	@Flip(name = "EditingEnabled", alterBean = "ContentResourceExtendedService.editingEnabled")
	public interface ContentResourceExtendedService {

		ContentDTO createNewContent(ContentDTO contentDTO);

		ContentDTO findOne(Long contentId);

		ContentRelationDTO addRelationBetweenContents(Long fromContentId, Long toContentId, String relationType);

		ContentCustomParametersModel getContentCustomParameters(Long contentId);

		Long updateContentCustomParameters(String jsonParameters, Long contentId);
	}

The base implementation:

	@Service("ContentResourceExtendedService.editingDisabled")
	@Transactional
	public class EditingDisabledContentResourceExtendedService implements ContentResourceExtendedService {

		private static final Logger log = LoggerFactory.getLogger(EditingDisabledContentResourceExtendedService.class);

		private final ContentService contentService;

		private final ContentExtendedRepository contentExtendedRepository;

		public EditingDisabledContentResourceExtendedService(ContentService contentService,
			ContentExtendedRepository contentExtendedRepository) {
			this.contentService = contentService;
			this.contentExtendedRepository = contentExtendedRepository;
		}

		@Override
		public ContentDTO createNewContent(ContentDTO contentDTO) {
			log.debug("Request to save Content : {}", contentDTO);
			throw new RuntimeException("Editing disabled");
		}
		...
	}	

And the alternate implementation:

	@Service("ContentResourceExtendedService.editingEnabled")
	@Transactional
	public class EditingEnabledContentResourceExtendedService implements ContentResourceExtendedService {

		@Override
		public ContentDTO createNewContent(ContentDTO contentDTO) {
			log.debug("Request to save Content : {}", contentDTO);
			...
		}
		...
	}

The resource gets the service as follows:

	@RestController
	@RequestMapping("/main/api/v3/course/structure/content")
	@Api(value = "Content")
	public class ContentExtendedResource {

		private final ContentResourceExtendedService contentResourceExtendedService;

		public ContentExtendedResource(
			@Qualifier("ContentResourceExtendedService.editingDisabled") ContentResourceExtendedService contentResourceExtendedService) {
			this.contentResourceExtendedService = contentResourceExtendedService;
		}

		...
	}

And finally, here is the configuration of FF4J:

	@Configuration
	@ComponentScan(basePackages = {"org.ff4j.spring.boot.web.api.resources", "org.ff4j.services", "org.ff4j.aop"})
	@AutoConfigureBefore(value = {WebConfigurer.class, DatabaseConfiguration.class})
	public class FF4jConfiguration extends SpringBootServletInitializer {

		/**
		 * Default URL.
		 */
		public static final String FF4J_WEBCONSOLE_URL = "ff4j-web-console";

		/**
		 * logging.
		 */
		private final Logger log = LoggerFactory.getLogger(FF4jConfiguration.class);

		/**
		 * User services of Jhispter to be used in FF4j.
		 */
		private final AuditEventRepository auditServices;

		@Value("${ff4j.core.autocreate}")
		private boolean enableAutoCreate = false;

		@Value("${ff4j.audit.enabled}")
		private boolean enableAudit = true;

		@Value("${ff4j.audit.log2jhispter}")
		private boolean log2Jhipster = true;

		/**
		 * Inject JHipster Settings.
		 */
		public FF4jConfiguration(AuditEventRepository audit) {
			this.auditServices = audit;
		}

		@Bean
		public FF4j getFF4j() {
			FF4j ff4j = new FF4j();

			ff4j.setFeatureStore(new FeatureStoreSpringJdbc(hikariDataSource));
			ff4j.setPropertiesStore(new PropertyStoreSpringJdbc(hikariDataSource));
			ff4j.setEventRepository(new EventRepositorySpringJdbc(hikariDataSource));

			// Wrapper to log also in JHISPTER AUDIT
			if (log2Jhipster) {
				ff4j.setEventRepository(new JHipsterEventRepository(
					ff4j.getEventRepository(), auditServices));
			}

			FF4JCacheManager ff4jCache = new CacheManagerHazelCast();
			FF4jCacheProxy cacheProxy = new FF4jCacheProxy(ff4j.getFeatureStore(), ff4j.getPropertiesStore(), ff4jCache);
			ff4j.setFeatureStore(cacheProxy);
			ff4j.setPropertiesStore(cacheProxy);

			ff4j.audit(enableAudit);
			ff4j.autoCreate(enableAutoCreate);
			ff4j.setAuthorizationsManager(new JHipsterAuthorizationManager());
			return ff4j;
		}

		//-------- SQL ----------

		// DataSource
		private HikariDataSource hikariDataSource;

		@Autowired(required = false)
		public void setHikariDataSource(HikariDataSource hikariDataSource) {
			this.hikariDataSource = hikariDataSource;
		}

		@Bean
		public ServletRegistrationBean ff4jDispatcherServletRegistrationBean(FF4jDispatcherServlet ff4jDispatcherServlet) {
			return new ServletRegistrationBean(ff4jDispatcherServlet, "/" + FF4J_WEBCONSOLE_URL + "/*");
		}

		@Bean
		public FF4jDispatcherServlet getFF4jDispatcherServlet(FF4j ff4j) {
			FF4jDispatcherServlet ff4jConsoleServlet = new FF4jDispatcherServlet();
			ff4jConsoleServlet.setFf4j(ff4j);
			return ff4jConsoleServlet;
		}
	}

I start the app, call my endpoint and get the Exception as foreseen because the feature isn't created nor enabled.
I go to the FF4J console, create the feature and enable it, which can be seen in the logs:
`2018-02-15 15:02:10.782  INFO 20154 --- [ XNIO-2 task-13] org.ff4j.web.embedded.ConsoleOperations  : EditingEnabled has been created
2018-02-15 15:02:15.303  INFO 20154 --- [  XNIO-2 task-6] o.f.web.controller.FeaturesController    : EditingEnabled has been enabled`

I call my endpoint again but I still get the exception.
I tried to debug the FeatureAdvisor by setting breakpoints in the invoke method but it seems that in my case, it's never called.

Do you see any reason ? Could it be because of the injection via constructors ?

**Comment by anthonyrichir** [comment]
Anyone still active on this project  ?

**Comment by clun** [comment]
Yes, there is. Just changing at the moment doesn't help. 

The problem is known and due to JHipster with stacks and stacks of advisors/interceptors adn ver scan the classes and annotations. Maybe there is a a way to tell Spring to orchestrate the advisors.

So far it works with the been FF4j & not the AOP.  I assume they will update Spring boot version soon.

**Comment by clun** [comment]
At this point I won't retro-engineering the JHispter stack and all interceptors. Any luck on you side ?
