### ISSUE TITLE
Trying to combine Features Strategies with ExpressionFlipStrategy 

### ISSUE THREAD

**Issue by garrablanca** [ff4j/ff4j#294]
By using **ExpressionFlipStrategy** to combine the validation of an strategies used by a feature, let say...

**FeatureA** has an **Case1FlippingStrategy** where [**_pointsGreaterThan = 20_**], and the Toggle is **ON**
and
**FeatureB** has an **Case2FlippingStrategy** where [**_userGrantedID = 10001,10002_**], and the Toggle is **ON**
and
**FeatureC** has an **ExpressionFlipStrategy** where [**_expression=FeatureA AND FeatureB_**], and the Toggle is **ON**

And We use only **FeatureC** on the code to do something...

### RESULT:
**The result here is that no matter is the Strategies complies with the conditions what it's matter is if the Toggle value is ON or OFF on the Feature used by the expression.**
### EXPECTATION:
**What we expect is that in the expression should result valid if the Strategies comply with the evaluations of each features used combined into this expression.**

The intention is that we can add more Features with more Strategies and combine all of them in an interesting Expression Strategy.

**Comment by clun** [comment]
It makes sense and I totally agree.

As you mentioned, unfortunately so far we relied on the status of features `https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/strategy/el/ExpressionFlipStrategy.java#L88` as most difficult part of the dev was to create the syntax tree analyzer...

Let's update this

**Comment by clun** [comment]
That is expected,  this is current algorithm:
- Check that feature is toggled, if KO exit
- if OK check that there is security policies, if KO exit
- if OK check the custom strategies
So for featureC to be enabled you also need A and B to be enabled.

If you don't want to rely on status of other feature you should provide the full condition or use the drool plugin.
