### ISSUE TITLE
Resetting number of rows to show in the Admin Console lists.

### ISSUE THREAD

**Issue by garrablanca** [ff4j/ff4j#295]
In the Admin Console once one set up the number of rows, is not keeping the value to show anytime when  one returns to the same page or reload the page.
![image](https://user-images.githubusercontent.com/11811349/36855954-d1a02ace-1d42-11e8-9b31-854951896e83.png)
One have to set this value every time one returns to the page that require it, and it's quite annoying.

Regards

**Comment by clun** [comment]
Ack got that. 

This settings is all about JS and datatable. 

Will see how I can improve that, maybe with a cookie.

**Comment by clun** [comment]
Checked and unfortunately there is no way for me to override the library JS setting.
