### ISSUE TITLE
Problem with table schema

### ISSUE THREAD

**Issue by ilfernandes** [ff4j/ff4j#296]
i  started using ff4j and got a issue with table schema

i use table with different schemas like SCHEMA.TABLE_NAME
i.e: "ian"."FF4J_FEATURES" (i have to use a schema)

The way i found to create table with schema i did as explained here:
https://github.com/ff4j/ff4j/issues/104

but when i call ff4j.createSchema() it tries to create the table even if table exists  bcz  de JdbcUtils.isTableExist is passing the table schema as null.

is there another way? 

thanks

**Comment by clun** [comment]
PR merged

**Comment by clun** [comment]
Part of 1.8.x
