### ISSUE TITLE
Wiki Documentation Bad Wording

### ISSUE THREAD

**Issue by NicoTexas** [ff4j/ff4j#298]
From the Wiki https://github.com/ff4j/ff4j/wiki/Web-Concepts#securing-accesses-to-api
"You may notice that i each implement you can secured the API using ApiKey of Basic Authentication."

This is not very clear what you want to convey here. I could help maybe but not 100% sure of the meaning.

**Comment by clun** [comment]
Fixed. 
https://github.com/ff4j/ff4j/wiki/Web-Concepts#securing-accesses-to-api

You choose either to expect ApiKey in the header or use standard HTTP-Basic Authentication headers.
