### ISSUE TITLE
css and other resources not found in ff4j console 1.7 

### ISSUE THREAD

**Issue by enricjaen** [ff4j/ff4j#300]
Hello, I can access the ff4j console (version 1.7) but without styles, as I get 404 in all the other resources (css, js, ...)

GET /customer/ff4j-console HTTP/1.1" 200 14883
GET /customer/static/css/style.css HTTP/1.1" 404 4814
GET /customer/static/img/flags/flagEnglish.png HTTP/1.1" 404 4814

I see they are embedded in the ff4j-web-1.7.1.jar  , but not sure how these resources can be found by the servlet as they arent under the war's root

**Comment by clun** [comment]
Ok this is an issue of ThymeLeaf, you have to add a `/` and the end of the URL

+ if you are using spring-boot-2.0 you will need to add the dependency javax.activation.

**Comment by enricjaen** [comment]
with "/" I get 404

GET /customer/ff4j-console/ HTTP/1.1" 404 4814

I am using javax.activation, however my app uses spring, not spring boot

**Comment by sebrouss** [comment]
Same issue here.

Without the / at the end of the URL : 404 on multiple ressources 
With the / at the end : 404 on ff4-console ressource

 FYI : 
- I use jersey 2 to expose rest services within my application
- "Old" embedded console works fine

**Comment by clun** [comment]
Hi,

I updated the sample to 1.7.1, it works to me

- [ff4j-sample-web](https://github.com/ff4j/ff4j-samples/tree/master/ff4j-sample-web) to start with  `mvn jetty:run`
- [ff4j-sample-spring-boot](https://github.com/ff4j/ff4j-samples/tree/master/ff4j-sample-springboot) to start with `mvn spring-boot:run` 

Please note I am actively working on `1.7.2` and expect to have something in a couple of days. 

Next we will have 
- `1.8.x` upgrading to JDK8
- `2.x` work in progress with heavy refactoring only having JDBC for now
