### ISSUE TITLE
Error 404 on http://www.ff4j.org/taglibs/ff4j

### ISSUE THREAD

**Issue by Matthieu-L** [ff4j/ff4j#301]
Hi,
Following the [documentation](https://github.com/ff4j/ff4j/wiki/Web-Concepts#taglib) the URL to include in JSP is http://www.ff4j.org/taglibs/ff4j
like this : 
`<%@ taglib prefix="ff4j" uri="http://www.ff4j.org/taglibs/ff4j" %>`
But at this moment it's return an 404  error

There something missing ?

**Comment by clun** [comment]
Hi,

`ff4j.org` is now down and replace by `ff4j.github.io` xsd will be found here `https://ff4j.github.io/schema/ff4j-1.6.xsd`
