### ISSUE TITLE
UI Problem Specific to ExpressionFlippingStrategy

### ISSUE THREAD

**Issue by kevinsu2496** [ff4j/ff4j#304]
Can't use the special character '&' to create an expression strategy. (e.g. A & B). The '|' works fine but the parenthesis also does not parse correctly. Need to also add function to parse 'AND' as an '&' operator and same with 'OR' for '|' operator. Thanks!

**Comment by clun** [comment]
Hi,

Do you have a sample expression with parenthesis running issues ? I have a bund of pretty [advanced unit tests](https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/test/java/org/ff4j/test/strategy/el/ExpressionParserTest.java#L116-L161
) maybe I am missing something.

This error may occurs if you are using XML files, you need to escape the special charaters.

**Comment by clun** [comment]
The only way to work with special characters here is to espace them with `\` before.
