### ISSUE TITLE
Getting Started code doesn't run

### ISSUE THREAD

**Issue by joewarner** [ff4j/ff4j#306]
I'm trying to run the HelloTest code from the Getting Started guide. I see a note that says that it is 1.3 code that needs upgrading to 1.6 (or even 1.7.1 that I have). But even trying to take that into consideration it seems like it should run. I think I see several problems

1. it fails `assertNotNull(getClass().getClassLoader().getResourceAsStream("ff4j.xml");` but the file is there because I can do `assertTrue((new File("ff4j.xml")).exists());`
1. So, if I comment the above assert, then it fails on `FF4j ff4j = new FF4j("ff4j.xml");` with the following stack trace

```
java.lang.IllegalArgumentException: Cannot parse feature stream
	at org.ff4j.store.InMemoryFeatureStore.loadConf(InMemoryFeatureStore.java:102)
	at org.ff4j.store.InMemoryFeatureStore.loadConfFile(InMemoryFeatureStore.java:91)
	at org.ff4j.store.InMemoryFeatureStore.<init>(InMemoryFeatureStore.java:58)
	at org.ff4j.FF4j.<init>(FF4j.java:141)
```

Now `org.ff4j.store.InMemoryFeatureStore.loadConfFile(InMemoryFeatureStore.java:91)` is just another `getClass().getClassLoader.getResourceAsStream()` call returning `null`. 

I'm struggling to see what I have missed. My compiler is Java8 although I doubt the code is that modern - more likely to be Java5 standard I assume. I'm not seeing why it doesn't run.

**Comment by clun** [comment]
Hi,

Issue seems to be related to `ff4j.ml` not part of your classpath. Did you manage to make the sample work. You may find a lot of working samples [here](https://github.com/ff4j/ff4j-samples).
