### ISSUE TITLE
Why FF4j doesn't support working with Hibernate?

### ISSUE THREAD

**Issue by tuannguyenoddle** [ff4j/ff4j#307]
I would like using FF4j with Hibernate in my project. Does FF4j supported working with Hibernate or not? Do we have any example to do it.

**Comment by clun** [comment]
Hi,

FF4j will perform CRUD operations on different stores technologies. It will update Features, Properties Events, MetaData. We might think it is a good place for **Hibernate,** any **JPA** or even **Spring Data** and , well, yes it is.

Yet, if you have hooked objects (proxifed by cglib proxies created by hibernate) you may run into trouble
- if someone update the bean without flush or saving. The next CHECK will have to look at the DB each time _(specially as there is some cache to avoid accessing the DB each time)_
- you will unmarchall object at each check and increase overhead to check value
- If i annotated beans (Features, Properties) for this Hubernate I need to drag the dependencies even when you don't need it.

I am partial, I have never liked hibernate, personal feeling, I can work with it but it leads to many, many-to-many errors for no real added value :)  think `OpenSessionInViewFilter`...

Now I am totally opened to a pull request with an implementation of JDBC store using hibernate, you could get some insight looking at [CassandraStore](https://github.com/ff4j/ff4j/blob/master/ff4j-store-cassandra/src/main/java/org/ff4j/cassandra/store/FeatureStoreCassandra.java#L66) or JDBC Stores extends `AbstractFeatureStore`.
