### ISSUE TITLE
java.lang.NoSuchMethodError exception in org.ff4j:ff4j-webapi caused by dependency conflict with org.apache.commons:commons-lang3:jar

### ISSUE THREAD

**Issue by LeoAugust19** [ff4j/ff4j#309]
Hi, dependency conlict issue exists in ff4j/ff4j-webapi. As shown in the following dependency tree, this project directly depends on io.swagger:swagger-core:jar:1.5.4, and io.swagger:swagger-core:jar:1.5.4 depends on org.apache.commons:commons-lang3:jar:3.2.1, based on Maven's dependency management mechanism, the org.apache.commons:commons-lang3:jar:3.0 wins version 3.2.1.

Dependency tree:

org.ff4j:ff4j-webapi:jar:1.7.1
|  +- io.swagger:swagger-core:jar:1.5.4:compile
|  |  +- org.apache.commons:commons-lang3:jar:3.0:compile (version managed from 3.2.1)

However, by static analysis, method **org.apache.commons.lang3.StringUtils.prependIfMissing(Ljava/lang/String;Ljava/lang/CharSequence;[Ljava/lang/CharSequence;)Ljava/lang/String** is referenced by the host project and only defined in org.apache.commons:commons-lang3:jar:3.2.1, which may cause a java.lang.NoSuchMethodError exception.

The solution is to force version org.apache.commons:commons-lang3:jar:3.2.1 to be loaded.

Hope this report can help you. Thanks! ^_^

**Comment by clun** [comment]
Please do, busy days to me, even if it summer..

**Comment by clun** [comment]
Preparing v1.7.2

**Comment by clun** [comment]
1.7.2 released
