### ISSUE TITLE
FF4J AOP CGLIB proxied classes

### ISSUE THREAD

**Issue by FelipeAdorno** [ff4j/ff4j#310]
Hi @clun I try use FF4J Flip with CGLIB proxy but doesn't work and I see the problem. 
The class [https://github.com/ff4j/ff4j/blob/1.7.x/ff4j-aop/src/main/java/org/ff4j/aop/FeatureAutoProxy.java](url) can't get the interface annotated with Flip from a proxy class I solved the problem changing this point at method getAdvicesAndAdvisorsForBean:

```
if (!beanClass.isInterface()) {
            Class<?>[] interfaces;
            if (ClassUtils.isCglibProxyClass(beanClass)) {
                interfaces = beanClass.getSuperclass().getInterfaces();
            } else {
                interfaces = beanClass.getInterfaces();
            }

            if (interfaces != null) {
                for (Class<?> currentInterface: interfaces) {
                    Object[] r = scanInterface(currentInterface);
                    if (r != null) {
                        return r;
                    }
                }
            }
        }
```

This works for me, what do you think about this? If make sense I'll fire a PR.

**Comment by clun** [comment]
Yes it makes totally sense, please send PR.
