### ISSUE TITLE
WebConsole ClearCache button does not work with Redis

### ISSUE THREAD

**Issue by j-flex** [ff4j/ff4j#312]
The clearFeatures and clearProperties methods in FF4jCacheManagerRedis appear to be set up to clear the feature and properties keys using a pattern, which is not supported by Redis. Instead, the actual key names need to be passed into the Jedis del method (ex: FF4J_FEATURE_feature1 and FF4J_FEATURE_feature2 rather than only FF4J_FEATURE_*). This causes the ClearCache button in the web console to not be functional when using FF4jCacheManagerRedis. 

I was able to get this working using the below for clearing features:

```
public void clearFeatures()  {
        Set<String> matchingKeys = new HashSet<>();
        ScanParams params = new ScanParams();
        params.match(KEY_FEATURE + "*");

        Jedis jedis = null;
        try {
            jedis = getJedis();

            String cursor = "0";

            do {
                ScanResult<String> scanResult = jedis.scan(cursor, params);
                List<String> keys = scanResult.getResult();
                cursor = scanResult.getStringCursor();

                matchingKeys.addAll(keys);
            } while (!cursor.equals("0"));

            if (matchingKeys.isEmpty()) {
                return;
            }

            jedis.del(matchingKeys.toArray(new String[matchingKeys.size()]));
        } finally {
            if (jedis != null) {
                jedis.close();
            }
        }
    }
```

**Comment by clun** [comment]
https://github.com/ff4j/ff4j/blob/master/ff4j-store-redis/src/main/java/org/ff4j/cache/FF4jCacheManagerRedis.java#L108-L116

**Comment by clun** [comment]
part of 1.7.2
