### ISSUE TITLE
Dependency conflict issue cause by ch.qos.logback:logback-core:jar

### ISSUE THREAD

**Issue by LeoAugust19** [ff4j/ff4j#315]
Hi, as shown in the following dependency tree, there is a dependency conflict issue in your project **org.ff4j:ff4j-spring-boot-autoconfigure:jar:1.7.1**. Due to Maven version management, only **ch.qos.logback:logback-core:jar:1.1.11** can be loaded  (version 1.1.2 will be shadowed), during the packaging process.

However, method **<ch.qos.logback.core.util.Loader: java.util.Set getResourceOccurrenceCount(java.lang.String,java.lang.ClassLoader)>** only exits in logback-core 1.1.2. "Java.lang.NoSuchMethodError" may be thrown, when your project invoking the missing method -------

### Dependency tree
org.ff4j:ff4j-spring-boot-autoconfigure:jar:1.7.1
+- org.springframework.boot:spring-boot:jar:1.5.4.RELEASE:compile
|  +- org.springframework:spring-core:jar:4.2.3.RELEASE:compile (version managed from 4.3.9.RELEASE)
|  |  \- commons-logging:commons-logging:jar:1.2:compile
|  \- org.springframework:spring-context:jar:4.2.3.RELEASE:compile (version managed from 4.3.9.RELEASE)
|     +- org.springframework:spring-aop:jar:4.2.3.RELEASE:compile
|     |  +- aopalliance:aopalliance:jar:1.0:compile
|     |  +- (org.springframework:spring-beans:jar:4.2.3.RELEASE:compile - omitted for duplicate)
|     |  \- (org.springframework:spring-core:jar:4.2.3.RELEASE:compile - version managed from 4.3.9.RELEASE; omitted for duplicate)
|     +- org.springframework:spring-beans:jar:4.2.3.RELEASE:compile
|     |  \- (org.springframework:spring-core:jar:4.2.3.RELEASE:compile - version managed from 4.3.9.RELEASE; omitted for duplicate)
|     +- (org.springframework:spring-core:jar:4.2.3.RELEASE:compile - version managed from 4.3.9.RELEASE; omitted for duplicate)
|     \- org.springframework:spring-expression:jar:4.3.9.RELEASE:compile (version managed from 4.2.3.RELEASE)
|        \- (org.springframework:spring-core:jar:4.2.3.RELEASE:compile - version managed from 4.3.9.RELEASE; omitted for duplicate)
+- org.springframework.boot:spring-boot-starter-web:jar:1.5.4.RELEASE:compile
|  +- org.springframework.boot:spring-boot-starter:jar:1.5.4.RELEASE:compile
|  |  +- (org.springframework.boot:spring-boot:jar:1.5.4.RELEASE:compile - omitted for duplicate)
|  |  +- (org.springframework.boot:spring-boot-autoconfigure:jar:1.5.4.RELEASE:compile - omitted for duplicate)
|  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.5.4.RELEASE:compile
|  |  |  +- **ch.qos.logback:logback-classic:jar:1.1.2:compile (version managed from 1.1.11)**
|  |  |  |  +- **ch.qos.logback:logback-core:jar:1.1.11:compile (version managed from 1.1.2)**
|  |  |  |  \- (org.slf4j:slf4j-api:jar:1.7.7:compile - version managed from 1.6.6; omitted for duplicate)
|  |  |  +- (org.slf4j:jcl-over-slf4j:jar:1.7.7:compile - version managed from 1.7.25; omitted for duplicate)
|  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
|  |  |  |  \- (org.slf4j:slf4j-api:jar:1.7.7:compile - version managed from 1.7.25; omitted for duplicate)
|  |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.25:compile
|  |  |     \- (org.slf4j:slf4j-api:jar:1.7.7:compile - version managed from 1.7.25; omitted for duplicate)
|  |  +- (org.springframework:spring-core:jar:4.2.3.RELEASE:compile - version managed from 4.3.9.RELEASE; omitted for duplicate)
|  |  \- org.yaml:snakeyaml:jar:1.17:runtime

### Solution
Upgrade logback-classic to 1.1.11 in parent-pom, or manage logback-core to version 1.1.2 in parent-pom.

Thanks!

Regards,
Leo

**Comment by LeoAugust19** [comment]
@clun I have pulled a request to fix this issue. Thanks.

**Comment by LeoAugust19** [comment]
@shoito The above information is obtained by static analysis. Do you need further information to confirm it's a bug? Maybe I can try to provide you more.

**Comment by LeoAugust19** [comment]
### Stack trace 
java.lang.NoSuchMethodError: ch.qos.logback.core.util.Loader.getResourceOccurrenceCount(Ljava/lang/String;Ljava/lang/ClassLoader;)Ljava/util/Set;
	at ch.qos.logback.classic.util.ContextInitializer.multiplicityWarning(ContextInitializer.java)
	at ch.qos.logback.classic.util.ContextInitializer.statusOnResourceSearch(ContextInitializer.java)
	at ch.qos.logback.classic.util.ContextInitializer.findConfigFileURLFromSystemProperties(ContextInitializer.java)
	at ch.qos.logback.classic.util.ContextInitializer.findURLOfDefaultConfigurationFile(ContextInitializer.java)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java)
	at org.ff4j.web.embedded.ConsoleServlet.<clinit>(ConsoleServlet.java)
	at org.ff4j.spring.boot.autoconfigure.FF4JWebConfiguration.getFF4jServlet(FF4JWebConfiguration.java:66)

**Comment by clun** [comment]
part of 1.7.2

**Comment by Twilio-functions9** [comment]
> Build is OK, version in 1.1.11 on master thanks.





https://stackdev.space/questions/using-logback-classic-with-jboss-and-spring
