### ISSUE TITLE
Swagger conflict

### ISSUE THREAD

**Issue by wurangbo** [ff4j/ff4j#317]
hi guys,
When I integrated FF4J into my project, I got the following error：
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'swaggerConfig' for bean class [org.ff4j.spring.boot.web.api.config.SwaggerConfig] conflicts with existing, non-compatible bean definition of same name and class [com.phoenix.common.swagger.SwaggerConfig]

**Comment by paul58914080** [comment]
Hello @wurangbo ,

Can you try using `@Qualifier('phoenixSwaggerConfig')` annotation on `com.phoenix.common.swagger.SwaggerConfig`

**Comment by wurangbo** [comment]
hi  I have tried,but it doesn't work!

**Comment by wurangbo** [comment]
hi @paul58914080 
I have tried, but it doesn't work.

**Comment by paul58914080** [comment]
Hello @wurangbo ,

Can you provide a gist of what you have tried ?

**Comment by paul58914080** [comment]
Hello @wurangbo ,

Can you provide a gist of what you have tried ?

**Comment by wurangbo** [comment]
Hi Paul,    I had to use toggle-z as replacement 发自我的iPhone------------------ Original ------------------From: Paul Williams  <notifications@github.com>Date: Wed,Feb 27,2019 11:20 PMTo: ff4j/ff4j <ff4j@noreply.github.com>Cc: wurangbo <wurangbo@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [ff4j/ff4j] Swagger conflict (#317)Hello @wurangbo ,
Can you provide a gist of what you have tried ?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ff4j/ff4j","title":"ff4j/ff4j","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ff4j/ff4j"}},"updates":{"snippets":[{"icon":"PERSON","message":"@paul58914080 in #317: Hello @wurangbo ,\r\n\r\nCan you provide a gist of what you have tried ?"}],"action":{"name":"View Issue","url":"https://github.com/ff4j/ff4j/issues/317#issuecomment-467902733"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ff4j/ff4j/issues/317#issuecomment-467902733",
"url": "https://github.com/ff4j/ff4j/issues/317#issuecomment-467902733",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
