### ISSUE TITLE
Thyme LeafDialects - Bug in Enable/Disable Processors

### ISSUE THREAD

**Issue by sasiperi** [ff4j/ff4j#319]
Hello Cedrick,

I have been following FF4J for past month or so and I am very impressed with the work your team is doing! I evaluated a few commercial ones, but they are still lagging behind some of the ideas that you are implementing (e.g most don't easily work with Spring Boot, do not support custom expressions or various Flip Strategies you thought through).

I created a sample application(s) to showcase almost every capability within Spring (SpringBoot app) space.   I came across a bug in ThymeLeaf Enable/Disable processors, with the following line in the "isVisible" method. 
The FFJ should have been injected or picked up from the context, to pick the correct FeatureStore that the FFJ application chooses to use.

       FF4j ff4j = new FF4j();
        return !ff4j.check(feature);

I fixed this by overriding the Dialects/Processors in my SpringBoot app and am able to use the Thymeleaf enable/disable prefixes successfully.
**Questions**
1.  I would like to contribute this to FF4J. Can you please let me know if/how can I do this?
2. What I have to contribute to?
  a) I have the above fix.
  b) I have a lot of sample code demonstrating  FF4J with a SpringBoot(ThymeLeaf web app).

Note:  
I also noted In a SpringBoot ThymeLeaf with Bootstrap CSS based webapp (ff4j 1.7.1) , when used as embedded app, FF4J styles are conflicted with BootStrap CSS when used with out LESS. So I am running FF4J as a separate appp (not the standalone one), and make all my SpringBoot apps connect to same feature store (e.g. Jdbc) as FF4J Web Console app for Features, and for the application specific needs it connects it's default DataSource (which is marked as @Primary).

**Comment by sasiperi** [comment]
As far as contributing to ff4j, I found the answer here:  https://github.com/ff4j/ff4j/blob/master/CONTRIBUTING.md
I will create pull request.

**Comment by clun** [comment]
Thymeleaf is not 3.0 with lastest release and think this one can be closed
