### ISSUE TITLE
build with java 10 throw exception Caused by: java.lang.ClassNotFoundException: java.sql.SQLException

### ISSUE THREAD

**Issue by doublepixyz** [ff4j/ff4j#329]
Maven: apache-maven-3.5.3
Java version: 10.0.2, vendor: Oracle Corporation
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-38-generic", arch: "amd64", family: "unix"

**Comment by clun** [comment]
Which build ? Working and delivering ff4j with jdk11 for months. Will close for now
