### ISSUE TITLE
shema-ddl.sql doesn't support PostgreSQL

### ISSUE THREAD

**Issue by obozek** [ff4j/ff4j#331]
There is problem with quotation of column names. It's anitpattern in Postgres to quote column names they become case sensitive. Column names in queries are not being recognised resulting in SQL errors.

**Comment by Infrag** [comment]
I can create MR with Postgres compatible .sql file.

**Comment by clun** [comment]
Would be nice of you - please add a suffix in the sql filename. 
I feel that this file has been updated multiple times depending on people and DB they were using.

**Comment by clun** [comment]
The file has been updated in between

**Comment by toellrich** [comment]
We've had the same problem. I was wondering why the quotes couldn't simply be removed. Do some databases require them?Alternatively, would it be possible to use upper case in the SQL queries? That should also fix the problem.

**Comment by clun** [comment]
sounds worth a try for minimal effort here

**Comment by toellrich** [comment]
Cool. What are you going for? Quotes removal or upper case in SQL? Either way, I can try it in our system once you have a release candidate.

**Comment by clun** [comment]
The current file is working with postgres. You can update your settings to be not case sensitive at postgres side or edit the `sql` file to match your settings.
