### ISSUE TITLE
Dependency conflicts on :org.slf4j:slf4j-api:jar, causing inconsistent semantic behavior

### ISSUE THREAD

**Issue by HelloCoCooo** [ff4j/ff4j#336]
Hi, in **ff4j-1.7.3** (ff4j-utils-json module), there are mulptiple versions of **org.slf4j:slf4j-api.jar**. However, according to Maven's dependency management strategy, only **org.slf4j:slf4j-api:jar:1.7.7** can be loaded, and **org.slf4j:slf4j-api:jar:1.7.22** will be shadowed.

As shown in the following dependency tree, **ch.qos.logback:logback-classic:jar:1.1.11** expects to reference **org.slf4j:slf4j-api:jar:1.7.22**, but due to dependency conflicts, Maven actually loads **org.slf4j:slf4j-api:jar:1.7.7**. As a result, **ch.qos.logback:logback-classic:jar:1.1.11** has to invoke the methods included in the unexpected version **org.slf4j:slf4j-api:jar:1.7.7**, which may cause inconsistent semantic behaviors.

For instance, method **org.ff4j.utils.mapping.JsonStringPropertyMapper: java.lang.String toStore(org.ff4j.property.Property)** actually references method **org.slf4j.helpers.MessageFormatter: org.slf4j.helpers.FormattingTuple arrayFormat(java.lang.String,java.lang.Object[])** in the unexpected version **org.slf4j:slf4j-api:jar:1.7.7** via the following invocation path:

```
<org.ff4j.utils.mapping.JsonStringPropertyMapper: java.lang.String toStore(org.ff4j.property.Property)> C:\Users\Flipped\Desktop\project\ff4j-utils-json\.\target\classes
<org.ff4j.property.Property: java.lang.String toJson()> C:\Users\Flipped\.m2\repository\org\ff4j\ff4j-core\1.7.3\ff4j-core-1.7.3.jar
<org.ff4j.property.util.PropertyJsonBean: void <init>(org.ff4j.property.Property)> C:\Users\Flipped\.m2\repository\org\ff4j\ff4j-core\1.7.3\ff4j-core-1.7.3.jar
<ch.qos.logback.classic.spi.LoggingEvent: java.lang.String toString()> C:\Users\Flipped\.m2\repository\ch\qos\logback\logback-classic\1.1.11\logback-classic-1.1.11.jar
<ch.qos.logback.classic.spi.LoggingEvent: java.lang.String getFormattedMessage()> C:\Users\Flipped\.m2\repository\ch\qos\logback\logback-classic\1.1.11\logback-classic-1.1.11.jar
<org.slf4j.helpers.MessageFormatter: org.slf4j.helpers.FormattingTuple arrayFormat(java.lang.String,java.lang.Object[])>
```

By further analyzing, the expected callee **org.slf4j.helpers.MessageFormatter: org.slf4j.helpers.FormattingTuple arrayFormat(java.lang.String,java.lang.Object[])** in shadowed version **org.slf4j:slf4j-api:jar:1.7.22**, have different implementations from the actual callees with the same signatures (same method names, same paremeters) included in the unexpected (but actual loaded) version **org.slf4j:slf4j-api:jar:1.7.7**, which leads to different behaviors.

### **Solution:**
Use the newer version **org.slf4j:slf4j-api:jar:1.7.22** to keep the version consistency.

**Dependency tree**---

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ ff4j-utils-json ---
[INFO] org.ff4j:ff4j-utils-json:jar:1.7.3
[INFO] +- org.ff4j:ff4j-core:jar:1.7.3:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.4:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.4:compile (version managed from 2.6.0)
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.6.4:compile
[INFO] +- org.ff4j:ff4j-test:jar:1.7.3:test
[INFO] |  +- (org.ff4j:ff4j-core:jar:1.7.3:test - omitted for duplicate)
[INFO] |  +- org.slf4j:jcl-over-slf4j:jar:1.7.7:test
[INFO] |  |  \- **org.slf4j:slf4j-api:jar:1.7.7:test**
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.1.11:test
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.1.11:test
[INFO] |  |  \- **(org.slf4j:slf4j-api:jar:1.7.7:test - version managed from 1.7.22; omitted for duplicate)**
[INFO] |  \- (junit:junit:jar:4.12:test - omitted for duplicate)
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test

```

Thanks,
Best regards,
Coco

**Comment by HelloCoCooo** [comment]
Code snippet of **org.slf4j.helpers.MessageFormatter: org.slf4j.helpers.FormattingTuple arrayFormat(java.lang.String,java.lang.Object[])** in **org.slf4j:slf4j-api:jar:1.7.7**:

![array1 7 7](https://user-images.githubusercontent.com/46306510/51961094-90876f00-2496-11e9-996f-5b3bffb4490d.png)

Code snippet of **org.slf4j.helpers.MessageFormatter: org.slf4j.helpers.FormattingTuple arrayFormat(java.lang.String,java.lang.Object[])** in **org.slf4j:slf4j-api:jar:1.7.22**:

![array1 7 22](https://user-images.githubusercontent.com/46306510/51961110-98dfaa00-2496-11e9-9c55-3fbb9a508617.png)

Method **org.slf4j.helpers.MessageFormatter: org.slf4j.helpers.FormattingTuple arrayFormat(java.lang.String,java.lang.Object[])** included in newer version **org.slf4j:slf4j-api:jar:1.7.22** splits the original control flows and add more new control flows and data flows. So Being forced to use older **org.slf4j:slf4j-api:jar:1.7.7** may lead to inconsisiten semantic behaviors.

**Comment by HelloCoCooo** [comment]
May I pull a request to fix it? 8)

**Comment by paul58914080** [comment]
@HelloCoCooo its open source. Ofcourse you can raise a pr . Contributions are most welcomed

**Comment by HelloCoCooo** [comment]
@paul58914080 Thanks for your reply. 8 )
