### ISSUE TITLE
Date picker CSS issue

### ISSUE THREAD

**Issue by vardarmo** [ff4j/ff4j#338]
In all tabs of monitoring section, date selection with date picker is very difficult, as there is a bug with showing the calendar. One column of the month is wider, and because of that, some other columns are not visible to be selected.

I investigated this, and found the cause of that. There is a custom rule in style.css file(line 1306), saying
.switch {
...
display: inline-block;
...
}

This display property should be removed, and the bug will be fixed.

**Comment by clun** [comment]
Very accurate issue and resolution, thank you. Will be part of `1.8.6` released this week-end.

Before:
<img width="287" alt="Screenshot 2020-05-09 at 02 49 30" src="https://user-images.githubusercontent.com/726536/81459434-3187ce00-91a0-11ea-9e61-7381d7f1c53b.png">

After
<img width="292" alt="Screenshot 2020-05-09 at 02 51 28" src="https://user-images.githubusercontent.com/726536/81459440-3a789f80-91a0-11ea-9df8-0c8be7a39e16.png">

**Comment by clun** [comment]
Part of 1.8.6 released today.
