### ISSUE TITLE
Web console , windows users with domain - cannot enter backslash in dialog

### ISSUE THREAD

**Issue by emwtur** [ff4j/ff4j#351]
using ff4j with windows users - getting username with domain eg DOMAIN\USER 
- cannot enter backslash from web console in "roles" dialog 
- if I enter users with backslash directly into database - I cannot edit the feature - but users look ok in list - and the names are read correctly in the "feature" check ( I have written my own code to check the users - it is a web application and I read the user in a .net api before I call my java api

**Comment by clun** [comment]
That's not surprising as \U is a special character. In the UI you should double this \\ and this should be fine

**Comment by emwtur** [comment]
Does not work - the dialog will not accept my "Valid" press if there are any \ in the dialog.
HOWEVER - I have solved the original problem in another way so this is not at problem for me !

/Per-Eric
