### ISSUE TITLE
Allow FF4J Execution Context to be set with InheritableThreadLocal instead of ThreadLocal

### ISSUE THREAD

**Issue by mjeanroy** [ff4j/ff4j#354]
Hi @clun,

Currently, the `FlippingExecutionContext` is stored in the `ThreadLocal`. It works great, but it does not allow to access the current execution context from a child thread.
Would you be open to allow setting the `FlippingExecutionContext` strategy when creating the `FF4j` instance?

It could look like something like that;

```java
FF4j ff4j = new FF4j();
ff4j.setFlippingExecutionContextStrategy(new InheritableThreadLocalStrategy());
```

```java
interface FlippingExecutionContextStrategy {
    FlippingExecutionContext get();
}
```

```java
class InheritableThreadLocalStrategy implements FlippingExecutionContextStrategy {
    private final InheritableThreadLocal<FlippingExecutionContext> contexts;

    @Override
    public FlippingExecutionContext get() {
        return contexts.get();
    }
}
```

```java
class ThreadLocalStrategy implements FlippingExecutionContextStrategy {
    private final ThreadLocal<FlippingExecutionContext> contexts;

    @Override
    public FlippingExecutionContext get() {
        return contexts.get();
    }
}
```

In this suggestion, I use an interface to specify the `FlippingExecutionContext` strategy instead of a flag to allow implementing a custom one easily, but it can be a simple flag otherwise.

**Comment by clun** [comment]
Hi, sounds a good idea as it does not break things and allow a new extension point. Will work on it for next version, FYI I am back in the game.

**Comment by clun** [comment]
I wonder if the proper setter in `FF4j` class is enough already. 

If i add :

```java
public void setFlippingExecutionContext(ThreadLocal<FlippingExecutionContext> flippingExecutionContext) {
 this.flippingExecutionContext = flippingExecutionContext;
}
```

Then, as `InheritableThreadLocal` is a subclass of  `ThreadLocal` the following statement is correct. You would have to cast the use it.

```java
ff4j.setFlippingExecutionContext(new InheritableThreadLocal<FlippingExecutionContext>());
```

I can also probably use `InheritableThreadLocal` everywhere. WDYT ?

**Comment by clun** [comment]
I will close it for now, don't hesitate to reopen if the `setter` and `InheritableThreadLocal` are not enough.
