### ISSUE TITLE
Accessing Web Console

### ISSUE THREAD

**Issue by yuriron** [ff4j/ff4j#355]
I want to point all components of our system to same ff4j storage, like jdbc or redis. In addition i want to launch web console that will show current state of all features. However web console documentation is not so clear. Please assist how to configure web admin to same ff4j backend.

**Comment by drizztguen77** [comment]
In the samples there is a fully working spring boot 2 example called ff4j-sample-springboot2. It displays the swagger docs, provides access to the rest API and enables the swagger console all in a Spring Boot 2 application. Hopefully this will show you what you need to know.
https://github.com/ff4j/ff4j-samples/tree/master/ff4j-sample-springboot2
