### ISSUE TITLE
AuditTrail not working  with MongoDB

### ISSUE THREAD

**Issue by odedzicherman** [ff4j/ff4j#359]

**Comment by clun** [comment]
Indeed. Seems like Mongo is really bad at timeseries. This is not implemented at all.
https://github.com/ff4j/ff4j/blob/master/ff4j-store-mongodb-v3/src/main/java/org/ff4j/mongo/store/EventRepositoryMongo.java

Not sure if I can shape a query. I could make a try but probably won't fix.

**Comment by drizztguen77** [comment]
I have done a good amount of development lately with MongoDb and AWS DocumentDB (Mongo compatible). I can take a look at implementing the audit for Mongo.

**Comment by clun** [comment]
Would be great, as you can tell I really back to dev here. `1.8.5` is out and really put back project on track. Running after the 2.0 chimera is good but let the project not in good shape.

For the Event repository with Mongo you will create a dynamic query based on the critera in `EventQueryDefinition`(https://github.com/ff4j/ff4j/blob/e596cdbc6c89462415a4ef471eadd19a5d87f7df/ff4j-core/src/main/java/org/ff4j/audit/EventQueryDefinition.java#L36) also I created a Discord room to chat when you want : https://discord.gg/mh6WRZ

**Comment by drizztguen77** [comment]
I just created a PR to add the event auditing for mongodb.

**Comment by clun** [comment]
Merged ! Thks. Finishing the `AuthorizationManager` evolution and we ship this week-end

**Comment by clun** [comment]
Part of 1.8.6 released today.
