### ISSUE TITLE
Investigation around command "keys"

### ISSUE THREAD

**Issue by hlassiege** [ff4j/ff4j#360]
Hi,

We have migrated recently to Google Cloud Platform and we are now using Cloud Memory Store which is a managed instance of Redis.

We had several downtimes and it seems to be related to some usage of the command KEYS" of Redis (that should used SCAN instead according to their documentation : https://redis.io/commands/keys)

We are currently investigating the different libraries that could use keys and it seems that FF4jCacheManagerRedis is using it.

However I saw that you already discuss about that in this issue : https://github.com/ff4j/ff4j/issues/177
I'm not completely sure to understand what was the conclusion of this issue. 

Could you explain me when listCachedFeatureNames and listCachedPropertyNames are used ? (I don't find the code where it is used) ?

Thanks

**Comment by clun** [comment]
Dear, 

This ticket required an answer for so long, sorry about that @hlassiege, I am back in the game, lookk at the commit history you can tell :0

@ggerbaud did some work on the redis store last week, he may have some views here (not finger pointing or anything).

Shipping `1.8.6` and then I will check this redis store, we also have an evolution about using `RedisTemplate`

**Comment by hlassiege** [comment]
No problem. We don't have the problem anymore so I guess the modification proposed by @jonathan-perucca in #375 was merged

**Comment by clun** [comment]
The #375 PR is merged yes ! Thank you will then close this one. ✋
