### ISSUE TITLE
JSF question

### ISSUE THREAD

**Issue by gageller** [ff4j/ff4j#361]
I've been asked to try and implement ff4j in a JSF application. Is this possible?

Thanks,

Greg

**Comment by clun** [comment]
Hi, 

Sorry for the delay, the project was a bit on hold for me changing job. 

IMO there is not issue to integrate with JSF. We provide a taglib and work well. You can find some example using Jetty here : 
https://github.com/ff4j/ff4j-samples/tree/master/webapp-jetty/ff4j-sample-web

Specially have a look to this file [sampletags.jsp](https://github.com/ff4j/ff4j-samples/blob/master/webapp-jetty/ff4j-sample-web/src/main/webapp/sampletags.jsp)

```html
https://github.com/ff4j/ff4j-samples/blob/master/webapp-jetty/ff4j-sample-web/src/main/webapp/sampletags.jsp
...

 <ff4j:enable featureid="F1" shareHttpSession="">
            <a href="#" class="btn btn-success" >
                <i class="icon-check icon-white"></i>&nbsp;ENABLE
            </a>
</ff4j:enable>
```
