### ISSUE TITLE
Link is broken in documentation

### ISSUE THREAD

**Issue by cah-daniel-adams01** [ff4j/ff4j#362]
This link is broken in the documentation, in the Web API section:

http://ff4j.org/rest-api

**Comment by clun** [comment]
Need to update yes. For now doc is here : https://ff4j.github.io/rest-api/

And Swagger spec here : https://ff4j.github.io/rest-api/ff4j_1.6.5_swagger.json

**Comment by clun** [comment]
Website has been updated : text, sample codes, links. It is up now.
