### ISSUE TITLE
ff4j features api not working

### ISSUE THREAD

**Issue by kanchanagarwal3** [ff4j/ff4j#363]
FF4J version - 1.7
Spring Version - 4.3.12
Thymeleaf Version - 2.1.4

though localhost:port/cosnole/home is working
 but unable to load json through feature api (localhost:port/api/ff4j/store/features
Audit feature is set to true but still no insert in dB neither any change in UI

`public void initConf() {
			conf = new ApiConfig();
		conf.setFF4j(((BeanFactory) ctx).getBean(FF4j.class));
		 ff4j.setFeatureStore((FeatureStore) new JdbcEventRepository((DataSource)
		((BeanFactory) ctx).getBean(JndiObjectFactoryBean.class)));
		 EventRepository auditStore = new JdbcEventRepository((DataSource)
		 ((BeanFactory) ctx).getBean(JndiObjectFactoryBean.class));
		ff4j.setEventRepository(
				new JdbcEventRepository((DataSource) ((BeanFactory) ctx).getBean(JndiObjectFactoryBean.class)));
		ff4j.audit(true);
	
	}

	@Override
	protected ApiConfig getApiConfig() {
		System.out.println("I m in getApiCOnfig");
			if (conf == null) {
		initConf();
		}
		return conf;
	}

	public FF4j getFF4j() {
		if (conf == null) {
		initConf();
			}
		return conf.getFF4j();
	}`

web.xml
``
<servlet>
        <servlet-name>ff4j-api</servlet-name>
        <servlet-class>com.sun.jersey.spi.container.servlet.ServletContainer</servlet-class>
        <init-param>
            <param-name>javax.ws.rs.Application</param-name>
            <param-value>com.wdn.fmt.ApplicationFeatureProvider</param-value>
        </init-param>
    </servlet>

    
    <servlet>
        <servlet-name>ff4j-console</servlet-name>
       <servlet-class>org.ff4j.web.FF4jDispatcherServlet</servlet-class>
        
        <init-param>
            <param-name>ff4jProvider</param-name>
            <param-value>com.wdn.fmt.ApplicationFeatureProvider</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>

    
    <servlet-mapping>
        <servlet-name>spring-web</servlet-name>
        <url-pattern>/security/*</url-pattern>
    </servlet-mapping>

    
    <servlet-mapping>
        <servlet-name>ff4j-api</servlet-name>
        <url-pattern>/api/*</url-pattern>
    </servlet-mapping>

    
    <servlet-mapping>
        <servlet-name>ff4j-console</servlet-name>
        <url-pattern>/console/*</url-pattern>
    </servlet-mapping>

Please suggest .I m completely novice in it

**Comment by clun** [comment]
Should you consider to run one of our sample 👍 specially this one as it is pretty quick : https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-springboot2x

**Comment by clun** [comment]
Looking at you config file you need to define the rest api services, here you only set the mapping here is a working https://github.com/ff4j/ff4j-samples/tree/master/webapp-jetty/ff4j-sample-web-api
