### ISSUE TITLE
Authentication for ff4j Web console.

### ISSUE THREAD

**Issue by PradeepKeshavprakash** [ff4j/ff4j#368]
Is there a way I can set authentication so that i can restrict access on who can access the ff4j web console?.

**Comment by clun** [comment]
Hi, unfortunately, this is NOT part of FF4j yet. 

The solution would be to leverage on spring Security in your app hosting the web console servlet.

**Comment by PradeepKeshavprakash** [comment]
Thanks, I'll have a check on that.

**Comment by manoharjangity** [comment]
Hi, 
I have two questions for ff4j implementation on my applicaiton. Could you please clarify the below:
1. Do we have any updates in recent ff4j releases for restricting ff4j console access?

2. I have ff4j configuration setup for my application as below: 
           web.xml:
             <servlet>
		<servlet-name>features-console</servlet-name>
		<servlet-class>......FF4jConsoleServlet</servlet-class> 
		<load-on-startup>1</load-on-startup>
	</servlet>
	<servlet-mapping>
		<servlet-name>features-console</servlet-name>
		<url-pattern>/features-console</url-pattern>
	</servlet-mapping>

      context.xml
             
	<bean id="ff4j" class="org.ff4j.FF4j">
 		<property name="featureStore" ref="featureStore" /> 
	</bean>
	
	<bean id="featureStore" class="org.ff4j.store.JdbcFeatureStore" >
		<property name="dataSource" ref="dataSource" />
	</bean>

How do I setup audit feature for this configuration? I tried to add below to set audit event repository, but failed with error:


	<bean id="ff4j" class="org.ff4j.FF4j">
 		<property name="featureStore" ref="featureStore" /> 
 		<property name="eventRepository" ref="eventRepository" /> 
	</bean>
	
	<bean id="featureStore" class="org.ff4j.store.JdbcFeatureStore" >
		<property name="dataSource" ref="dataSource" />
	</bean>
	
	<bean id="eventRepository" class="org.ff4j.audit.repository.JdbcEventRepository" >
		<property name="dataSource" ref="dataSource" />
	</bean>
	


09:44:09,297 ERROR [stderr] (ServerService Thread Pool -- 71) org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ff4j' defined in class path resource [applicationContext-jndiDataSource.xml]: Cannot resolve reference to bean 'eventRepository' while setting bean property 'eventRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eventRepository' defined in class path resource [applicationContext-jndiDataSource.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ff4j.audit.repository.JdbcEventRepository]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.ff4j.audit.repository.JdbcEventRepository.<init>()
09:44:09,300 ERROR [stderr] (ServerService Thread Pool -- 71)   at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
09:44:09,302 ERROR [stderr] (ServerService Thread Pool -- 71)   at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
09:44:09,304 ERROR [stderr] (ServerService Thread Pool -- 71)   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1533)
