### ISSUE TITLE
Documentation on ElasticSearch as storage is missing

### ISSUE THREAD

**Issue by emwtur** [ff4j/ff4j#369]

**Comment by emwtur** [comment]
There is very little documentation and no Example I think
( Looking at using FF4j in springboot with Elastic as storage)

**Comment by clun** [comment]
Hi sir,

This small sample happened to be that I had to rewrite the full store to be compliant we Elastic 6+.

Now, sir, you are covered:
- Documentation is [here](https://github.com/ff4j/ff4j/wiki/Store-Technologies#-elasticsearch)
- Sample Working Application is [here](https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-springboot2x-elastic) including a `docker-compose.yaml`.

Cheers.
