### ISSUE TITLE
FF4J pour une architecture microservices

### ISSUE THREAD

**Issue by sgrabou** [ff4j/ff4j#379]
Bonjour,

S'il vous plait, je travaille sur un projet au sein d'une architecture microservices avec springboot. j'ai plusieurs micro-services, chaque service a sa propre database,  je souhaite implémenter FF4j d'une manière à gérer la configuration de tous mes service en une seule console. c'est à dire, la configuration de FF4J est stocké dans une base de donné différente de celle utilisé par le micro-service Est ce possible ?

**Comment by clun** [comment]
Bonjour,

C'est tout a fait possible.

- Choisir la base dans laquelle on veut stocker les features (et/ou properties + events)
- On definit un composant "console" cote backend qui sera le seul a avoir la console
- On definit X composants avec FF4j qui pointe directement sur la meme base de donnees

Voici un exemple de code : https://github.com/ff4j/ff4j-demo-voxxeddays
Et la video de la presentation  https://www.youtube.com/watch?v=c1r-cnqelGA

Cheers

**Comment by sgrabou** [comment]
Merci beaucoup pour votre réponse. C'est très claire maintenant.

**Comment by mahwachi** [comment]
Bonjour,

les liens ci-dessus de l'exemple ne fonctionne plus, pourriez-vous le mettre a jour SVP. merci.

**Comment by clun** [comment]
Bien sur Voici le code de la video : https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-1x/ff4j-voxxeddays-ticino-2018

Sinon vous avez plusieurs exemples ici https://github.com/ff4j/ff4j-samples

Enfin n'hesitez pas a posez vos questions ici.

**Comment by mahwachi** [comment]
merci bien  @clun
