### ISSUE TITLE
Installing ff4j in clustter environment

### ISSUE THREAD

**Issue by mwjiang85** [ff4j/ff4j#383]
Hello,
We plan to use ff4j on an existing clustered Java app (4 nodes).  This requires that toggling a feature on/off from ff4j console has to apply to all nodes.  Will InMemoryFeatureStore or for instance, FeatureStoreDynamoDB work for clutter environment?  Any recommendations?

Thanks,

**Comment by clun** [comment]
Hi,

So for multiple instances of a service of multiple services sharing the same feature you need to use a Database to persist feature states. You create a dedicated component in the backend with ff4j-console and the microservices do not have the console. 

**Please have a look here for a sample :**  https://github.com/ff4j/ff4j-demo-voxxeddays
**Here is the talk about it** : https://www.youtube.com/watch?v=P6PtQtOYhus

Cheers

**Comment by clun** [comment]
Will close as response has been provided.
