### ISSUE TITLE
Getting Started wiki page: port option in wrong place, not exposing ports 

### ISSUE THREAD

**Issue by fkorling** [ff4j/ff4j#384]
The docker demo command on the Getting Started page in the wiki has the
-p option in the wrong place, not exposing the port.

On the page now: 

`docker run clunven/ff4j:ff4j-sample-springboot -p 8080:8080`

but should be: 

`docker run -p 8080:8080 clunven/ff4j:ff4j-sample-springboot`

**Comment by drizztguen77** [comment]
Thank you, this has been fixed.
