### ISSUE TITLE
Delegate isAllowed check to AuthorizationsManager

### ISSUE THREAD

**Issue by EricBustamante** [ff4j/ff4j#386]
I am trying to use ff4j with Apache Shiro permissions based authorization. The approach used by ff4j seems tied to role based authorization as seen by the isAllowed implementation.

https://github.com/ff4j/ff4j/blob/31a5847c87bce58663066f0c404befee85e66507/ff4j-core/src/main/java/org/ff4j/FF4j.java#L254-L270

Would it make sense that instead the FF4j class delegated the authorization logic to the AuthorizationsManager? Maybe include a isAllowed method on the AuthorizationsManager interface. With that approach I could handle role or permissions based authorization by implementing the AuthorizationsManager isAllowed method. This approach could also follow the "Tell, Don't Ask" principle.

**Comment by clun** [comment]
I agree with your findings. The updated  `AuthorizationsManager` will have same signature `isAllowed()` probably

**Comment by EricBustamante** [comment]
Nice 😃 In the meanwhile I made some customizations on my code to work around the issue. 
```java
public interface AuthorizationManager extends AuthorizationsManager {
    boolean isAllowed(Set<String> permissions);
}

public class ShiroAuthorizationManager implements AuthorizationManager {
    @Override
    public String getCurrentUserName() {
        return null;
    }

    @Override
    public Set<String> getCurrentUserPermissions() {
        return null;
    }

    @Override
    public Set<String> listAllPermissions() {
        return null;
    }

    @Override
    public String toJson() {
        return null;
    }

    @Override
    public boolean isAllowed(Set<String> permissions) {
        return SecurityUtils.getSubject().isPermittedAll(permissions.toArray(new String[0]));
    }
}

public class CustomAuthorizationFF4j extends FF4j {

    @Override
    public boolean isAllowed(Feature featureName) {
        // No authorization manager, returning always true
        if (getAuthorizationsManager() == null) {
            return true;
        }
        // if no permissions, the feature is public
        if (featureName.getPermissions().isEmpty()) {
            return true;
        }
        if (getAuthorizationsManager() instanceof AuthorizationManager) {
            return ((AuthorizationManager) getAuthorizationsManager())
                    .isAllowed(featureName.getPermissions());
        }
        return false;
    }
}
```

With those modifications I then set up FF4j as follows:
```java
AuthorizationManager authorizationManager = new ShiroAuthorizationManager();
FF4j ff4j = new CustomAuthorizationFF4j();
ff4j.setAuthorizationsManager(authorizationManager);
```

**Comment by clun** [comment]
Thanks for the nice idea. This is what it look like.

```java
public boolean isAllowed(Feature feature) {
  // No authorization manager, returning always true
  return (getAuthorizationsManager() == null) || 
  // if no permissions, the feature is public
  (feature.getPermissions().isEmpty()) ||
  // delegating evaluation to authorization manager
  getAuthorizationsManager().isAllowed(feature.getPermissions());
}
```

with

```java
default boolean isAllowed(Set<String> permissions) {
 // list intersection
 permissions.retainAll(getCurrentUserPermissions());
 return !permissions.isEmpty();
}        
```

Creating the module  `ff4j-security-shiro`ATM need some unit tests.

**Comment by clun** [comment]
Part of 1.8.6 released today.

Also you might like the new module `ff4j-security-shiro` with a working sample https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-security-shiro

**Comment by eric-bustamante** [comment]
I like the new implementation for the FFj4 `isAllowed` method. All logic contained in a single and concise expression that basically says: Return this or this other or this other.

We will adopt the new version ASAP, thank you! 🙂

**Comment by EricBustamante** [comment]
I like the new implementation for the FF4j `isAllowed` method. All logic contained in a single and concise expression that basically says: Return this or this other or this other.

We will adopt the new version ASAP, thank you! 🙂
