### ISSUE TITLE
ff4j-store-redis to support Jedis 3.1.0

### ISSUE THREAD

**Issue by VidyasagarGayakawad** [ff4j/ff4j#392]
I am using spring boot version. - 2.2.1.RELEASE. application uses redis as a database so I have dependency on org.springframework.data -> spring-data-redis with version 2.2.1.RELEASE which uses Jedis 3.1.0 version otherwise it fails to make a Jedis connection.

Now my application has a dependency on ff4j-store-redis which has a latest version 1.8.2 and can use Jedis 2.10.0 not the 3.1.0 hence, I am unable to use ff4j-store-redis with spring boot 2.2.1.RELEASE.

ERROR -

Caused by: java.lang.ClassNotFoundException: redis.clients.util.Pool

**Comment by VidyasagarGayakawad** [comment]
Team, do we have a plan to support above feature in ff4j ?

**Comment by VidyasagarGayakawad** [comment]
hello Team, could you please update us on this if you have this item in your priority list?

**Comment by VidyasagarGayakawad** [comment]
Team, pull request is raised for bumping up Jedis dependency versions in ff4j-redis-store. 
please check when time permits.
Thank you..!

**Comment by songokudbz** [comment]
And? Will this be available?

**Comment by clun** [comment]
Thks for poke Kakarotto. Time to ship a new version today.

**Comment by clun** [comment]
1.8.3 is on the central now :)

**Comment by clun** [comment]
Closing as merge and moved to 3.2.
