### ISSUE TITLE
FF4JProvider - Multiple Instances created when Web UI is used

### ISSUE THREAD

**Issue by kiranbpatil** [ff4j/ff4j#394]
Spring bean is defined as below and injected using spring DI
`<bean name="toggleService" class="com.company.service.toggle.ToggleService" scope="singleton"></bean>`

```
public class ToggleService implements FF4jProvider {
    private final FF4j ff4j;
    public ToggleService() {
        ff4j = new FF4j("ff4j.xml");
    }
    @Override public FF4j getFF4j() {
        return ff4j;
    }
}
```

I included the Admin UI dependency into the project and updated my web.xml as below
```
 <servlet>
        <servlet-name>ff4j-console</servlet-name>
        <servlet-class>org.ff4j.web.FF4jDispatcherServlet</servlet-class>
        <init-param>
            <param-name>ff4jProvider</param-name>
            <param-value>com.company.service.toggle.ToggleService</param-value>
        </init-param>
    </servlet>
    <servlet-mapping>
        <servlet-name>ff4j-console</servlet-name>
        <url-pattern>/ff4j-console/*</url-pattern>
    </servlet-mapping>
```

When my app loads, Spring  creates an instance of the `ToggleService` and so does the `FF4jDispatcherServlet`.  Due to this the data changed via one instance is unavailable for the other resulting in incorrect toggle values. 

Possible fix: `FF4jDispatcherServlet` should get the `ToggleService` instance if already created, rather than creating new one always

**Comment by kiranbpatil** [comment]
Check PR: https://github.com/ff4j/ff4j/pull/395

**Comment by clun** [comment]
Merged for a while, will close it now .
