### ISSUE TITLE
Thymeleaf TemplateProcessingException

### ISSUE THREAD

**Issue by igor-dmitriev** [ff4j/ff4j#397]
Version - 1.8.2

`org.thymeleaf.exceptions.TemplateProcessingException: Only variable expressions returning numbers or booleans are allowed in this context, any other datatypes are not trusted in the context of this expression, including Strings or any other object that could be rendered as a text literal. A typical case is HTML attributes for event handlers (e.g. "onload"), in which textual data from variables should better be output to "data-*" attributes and then read from the event handler. (template: "modal-features" - line 473, col 29)`

**Comment by ThiagoMontezano** [comment]
What version of thymeleaf are you using ?

I had the same problema with version 3.0.11.RELEASE but 3.0.9.RELEASE is ok.

**Comment by AfonsoFGarcia** [comment]
I'm experiencing the same issue. Thymeleaf 3.0.11.RELEASE with Spring Boot 2.2.2.RELEASE. Running SS4J Version 1.8.2.
