### ISSUE TITLE
EventRepositoryRedis uses different keys for storing and retrieving audit data

### ISSUE THREAD

**Issue by oemergenc** [ff4j/ff4j#399]
Hi,

i am trying to use the `EventRespositoryRedis` to store monitoring data. Unfortunately the web ui always stays empty. Switching to a `JdbcEventRepository` immediately solves the problem, so i guess my basic setup is okay. Here is a snippet of my ff4j configuration:
```
...
        val ff4j = new FF4j();
        ff4j.setFeatureStore(new JdbcFeatureStore(ds));
        ff4j.setPropertiesStore(new JdbcPropertyStore(ds));
        val redisConnection = new RedisConnection(redisHost, redisPort);
        ff4j.setEventRepository(new EventRepositoryRedis(redisConnection));
        ff4j.audit(true);
...
```
After digging into the code i can see, that for storing the data a key like this is used `"FF4J_EVENT_AUDITRAIL_20200113"` while for retrieving the data a key like this is used `"FF4J_EVENT_20200113".` Only the first key exists in my redis instance. 

Is there any magic behind this or is this a bug?

**Comment by oemergenc** [comment]
After digging into the code i think there might be a bug in the code of `getHashKey` function:

https://github.com/ff4j/ff4j/blob/master/ff4j-store-redis/src/main/java/org/ff4j/store/EventRepositoryRedis.java#L158-L159

As far as i can see, the `action` Parameter should not be null here:
https://github.com/ff4j/ff4j/blob/master/ff4j-store-redis/src/main/java/org/ff4j/store/EventRepositoryRedis.java#L328

**Comment by clun** [comment]
Sounds like a bug but a bit surprise that nobody noticed before. Investigating....

**Comment by clun** [comment]
Part of 1.8.6 released today.
