### ISSUE TITLE
do apache shiro version 1.4.2 supports jdk 1.7

### ISSUE THREAD

**Issue by kanchanagarwal3** [ff4j/ff4j#408]
At present we are using apache shiro 1.1.0 which is ruuning fine in jdk 1.7 
we are planning to upgrade it to 1.4.2 ..i want to know will it work fine in jdk 1.7 too
Maven compiler plugin which we are presently using is 2.3.2..do i need to upgrade that as well.

Please let me know what will be impacts on upgrading shiro version from 1.1 to 1.4.2

**Comment by clun** [comment]
`ff4j` 1.8.x work fine even with jdk11. You can update your Java version with confidence.

I have never used Shiro and don't know what would be the API changes from 1.1 to 1.4.2 . Tell me if you fine any issue.

**Comment by kanchanagarwal3** [comment]
Hi , how can i add this question in apache shiro...can you point me to that location...i m trying to figure out this answer relating to apache shiro

**Comment by clun** [comment]
To understand what change in Apache Chiro in the latest release I would recommend you go and ask in the [the Chiro user forum](http://shiro-user.582556.n2.nabble.com/)

To connect a FF4j `AuthenticationManager` on top of Chiro there is a sample in the issue. Would be nice to have a sample of Spring Boot App secured by Chiro and thus I could add FF4j in it as a sample.

**Comment by clun** [comment]
- Downloaded from https://github.com/apache/shiro/tree/shiro-root-1.4.2

```
cd shiro-shiro-root-1.4.2/samples/quickstart
```

edit the `pom.xml` to add
```xml
<plugin>
 <groupId>org.apache.maven.plugins</groupId>
 <artifactId>maven-compiler-plugin</artifactId>
 <version>3.3</version>
 <configuration>
  <source>1.7</source>
  <target>1.7</target>
  <showWarnings>false</showWarnings>
 </configuration>
</plugin>
```

```
mvn exec:java
```

So yes this is working but please move to latest version `1.5.3` and JDK1.8+ for Shira, maintaining open source in our spare time is challenging, maintaining old versions for people not paying any support is NO.
