### ISSUE TITLE
Audit and AOP : OK events published twice

### ISSUE THREAD

**Issue by ggerbaud** [ff4j/ff4j#409]
Hi,

We are using FF4J in my company and we really like it.

I am not sure this is really an issue but this is at least a discussion because it is annoying us.

I noticed that when we use a toggle with AOP and the toggle (and strategy) is active there are two "checkOn" events emitted but when toggle is off, only one off event.
When using ff4j#check directly only one event is emitted in both cases.

That seems to be a normal behavior (please confirm or not) : when using AOP, at least two proxies/interceptor are declared, for both primary and alter beans. So when bean is invoked, the feature is checked first on primary bean, and if OK, as the alter bean is invoked, the feature is checked again, with a second event.

See https://github.com/ff4j/ff4j/blob/master/ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java#L69 and https://github.com/ff4j/ff4j/blob/master/ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java#L84

So it seems to be normal but our statistics are therefore inconsistent

Is it really a feature that toggle is checked even for the alter bean ? 
I mean, what about doing the `!alterBean.equals(getExecutedBeanName(mi)))` (and the aletrClazz equivalent) before the call to `check(ff4jAnnotation, mi)` ?
I might be wrong but the call to `check(ff4jAnnotation, mi)` is useless when the invoke method is called for the alter bean (or alter class) because whatever the result, we will end up at line 96

What do you think ?

**Comment by clun** [comment]
Hi Guillaume,

Thanks for using `ff4j`.

Event `checkOn` should be triggered only ONCE to have consistent metrics either with AOP or not.

- If feature is not toggled
```java
boolean isFeatureToggled = check(ff4jAnnotation, mi);
```
returns false, going to ` return mi.proceed();` we are good

- If feature is toggled, we enter the bloc to `return invokeAlterBean(mi, alterBean);` that should finish by `method.invoke(alterbean, mi.getArguments());` L253. With this behaviours I tough I would only get a single event.

I am not sure why there are 2 interceptors. Did you put some annotation on the alterbean by any chance ? you don't have to. Will take a bit of time to investigate.

**Comment by ggerbaud** [comment]
Thanks for the quick reply.

If I take this example from [here](https://github.com/ff4j/ff4j/wiki/Advanced-Concepts#aspect-oriented-programming)

```java
public interface GreetingService {
 @Flip(name="language-french", alterBean="greeting.french")
 String sayHello(String name);
}

@Component
@Primary
public class GreetingServiceEnglishImpl implements GreetingService {
 public String sayHello(String name) {
  return "Hello " + name;
 }
}

@Component("greeting.french")
public class GreetingServiceFrenchImpl implements GreetingService {
  public String sayHello(String name) {
    return "Bonjour " + name;
  }
}
```
So [this method](https://github.com/ff4j/ff4j/blob/master/ff4j-aop/src/main/java/org/ff4j/aop/FeatureAutoProxy.java#L58) will be called for both beans (because of @Component).
As they have the same interface, with the @Flip annotation, the method will return PROXY_WITHOUT_ADDITIONAL_INTERCEPTORS and so there will be an interceptor for each.

Am I missing the point here ?

I am testing an evolution of FeatureAdvisor to prevent calling check when invoke is called for the alter bean.
Let me know if you would like a PR

**Comment by clun** [comment]
You are not missing the point that's definitively a bug on my end.

I would LOVE a PR like previous one for Redis, so much appreciated. I would engage to merge and release fast.

**Comment by ggerbaud** [comment]
So PR is here

**Comment by clun** [comment]
Part of 1.8.6 released today.
