### ISSUE TITLE
New Error in UI when going to FeatureStore

### ISSUE THREAD

**Issue by drizztguen77** [ff4j/ff4j#414]
With the new 1.8.6 version, when I try to go to the FeatureStore in the UI, it gives the following error and doesn't show the screen.

![image](https://user-images.githubusercontent.com/1878537/81584339-7b6ee080-9367-11ea-85ad-f103d63e9d23.png)

org.thymeleaf.exceptions.TemplateProcessingException: Could not parse as expression: "javascript:$('#modalRenameFeature #uid').val([[${feature.uid}]]);" (template: "modal-features" - line 456, col 21)

![image](https://user-images.githubusercontent.com/1878537/81584401-8e81b080-9367-11ea-88db-dd6d89ddc96e.png)

**Comment by clun** [comment]
Are you using spring boot 2.x ? (=Thymeleaf 3)
if spring-boot 1 then you are stuck in 1.8.2 for web I guess you cannot be compliant to both,

**Comment by drizztguen77** [comment]
We are on Spring Boot 2.1.10. I have this dependency for Thymeleaf. This was working in 1.8.4
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf</artifactId>
            <version>3.0.9.RELEASE</version>
        </dependency>

**Comment by clun** [comment]
mmmm I will do more tests this week like created a dedicated sample.

I can confirm so far:
- I changed the way to access variable in the UI between `1.8.4` and `1.8.5` like `.val([[${feature.uid}]]);` to cope with latest spring-boot or I ran into issue  (4.2 notation here) https://www.thymeleaf.org/doc/articles/thymeleaf3migration.html
- This is working with spring boot 2.2. (and ThymeleafAutoConfiguration  removed) https://ff4j-demo.herokuapp.com/ff4j-web-console/home

**Comment by drizztguen77** [comment]
I just changed to Spring Cloud Hoxton release and spring boot 2.2.7 and the console works fine there. I'm not sure if we can upgrade all our services to that or not. I'll have to see what it breaks when we do. I wonder what changed between spring boot 2.1 and 2.2 that causes it to break.

**Comment by clun** [comment]
The tag syntax changed in Thymeleaf 3.0.1 or close to adopt the `Textual template modes` now using squared brackets to access variables in loops.
https://www.thymeleaf.org/doc/articles/thymeleaf3migration.html

The only files I had to change to cope with Spring boot 2.2 was the HTML templates in `ff4j-web`. Technically speaking you can have everything all ff4j on `1.8.6` except` ff4j-web` in `1.8.4` that still make you change the `pom.xml`

With the answer I think we can close this issue.

**Comment by drizztguen77** [comment]
Yes that is perfect. Thank you for that information. It's working fine for us now.

**Comment by Sharma-K** [comment]
Hey, Can you please help me with this. I am facing this issue as well.
This is my main application file
```
package com.mint.pf.api;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;
import org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration;
import org.springframework.data.mongodb.config.EnableMongoAuditing;

@SpringBootApplication(exclude = {ThymeleafAutoConfiguration.class, SecurityAutoConfiguration.class})
//@SpringBootApplication
@EnableMongoAuditing
public class PersonalFinanceApplication {

    public static void main(String[] args) {
       SpringApplication.run(PersonalFinanceApplication.class, args);
    }



}

```
This is my pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
       <groupId>org.springframework.boot</groupId>
       <artifactId>spring-boot-starter-parent</artifactId>
       <version>2.0.0.RELEASE</version>
       <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.mint</groupId>
    <artifactId>personal-finance</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>personal-finance</name>
    <description>API Services Project for Personal FInance Rest API's</description>
    
    <properties>
       <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
       <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
       <java.version>1.8</java.version>
       <ff4j.version>1.8.13</ff4j.version>
    </properties>
    
    <dependencies>
       <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-web</artifactId>
       </dependency>
       
       <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-test</artifactId>
          <scope>test</scope>
       </dependency>
       
       <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-data-mongodb</artifactId>
       </dependency>
       
       <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-data-redis</artifactId>
       </dependency>
       
       <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-aop</artifactId>
       </dependency>

       <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-mail</artifactId>
       </dependency>
       
       <dependency>
          <groupId>org.projectlombok</groupId>
          <artifactId>lombok</artifactId>
          <scope>provided</scope>
       </dependency>
     
       <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-thymeleaf</artifactId>
          <version>2.0.0.RELEASE</version>
       </dependency>
       <dependency>
          <groupId>org.ff4j</groupId>
          <artifactId>ff4j-spring-boot-starter</artifactId>
          <version>1.8.13</version>
       </dependency>
       <dependency>
          <groupId>org.ff4j</groupId>
          <artifactId>ff4j-web</artifactId>
          <version>1.8.13</version>
       </dependency>
<!--       <dependency>-->
<!--          <groupId>org.ff4j</groupId>-->
<!--          <artifactId>ff4j-store-mongodb</artifactId>-->
<!--          <version>1.8</version>-->
<!--       </dependency>-->
    </dependencies>

    <build>
       <plugins>
          <plugin>
             <groupId>org.springframework.boot</groupId>
             <artifactId>spring-boot-maven-plugin</artifactId>
          </plugin>
       </plugins>
    </build>

</project>
```
