### ISSUE TITLE
XmlParser.exportFeatures produses invalid xml for custom property values

### ISSUE THREAD

**Issue by Exidex** [ff4j/ff4j#415]
XmlParser.exportFeatures generates:
```xml
  <feature uid="feature1" description="desc1" enable="true">
   <custom-properties>
    <property name="prop1" value="https://en.wikipedia.org/w/index.php?title=XML&action=edit&section=3" />
   </custom-properties>
  </feature>
```
while it should generate:
```xml
  <feature uid="feature1" description="desc1" enable="true">
   <custom-properties>
    <property name="prop1" value="https://en.wikipedia.org/w/index.php?title=XML&amp;action=edit&amp;section=3" />
   </custom-properties>
  </feature>
```
https://github.com/ff4j/ff4j/issues/63 is similar issue but for ExpressionFlipStrategy
I suggest using proper xml serialization instead of hand written string concatenation, which probably    doesn't handle other corner cases

**Comment by clun** [comment]
Got it we need to escape XML characters when generating `XML` file.

Will take some part of (with proper license references) https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/StringEscapeUtils.java

`ff4j-core` has no dependency what so ever and unfortunately there is no XML serialiser in the JDK except SAX. (JAXB is gone). In v2 the parsing is externalised and you can load from both XML and YAML but you can also provide you own loader.

**Comment by clun** [comment]
Escaping XML is not that difficult as only a few characters are invalid. The following code did the trick.

```java
public static String escapeXML(String input) {
        if (null == input) return input;
        return input .replaceAll("&", "&amp;")
             .replaceAll(">", "&gt;").replaceAll("<", "&lt;")
             .replaceAll("\"", "&quot;").replaceAll("\'", "&apos;");
    }
    
    public static String unEscapeXML(String input) {
        if (null == input) return input;
        return input.replaceAll("&amp;","&").replaceAll("&gt;", ">")
                    .replaceAll("&lt;", "<").replaceAll("&quot;", "\"")
                    .replaceAll("&apos;", "'");
    }
```

I used the following XML for my tests XML <==> Java Objects
https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/test/resources/test-parser-specialchars.xml

And tested in the following TEST:
https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/test/java/org/ff4j/test/parser/XmlParserTest.java#L108-L137

This will be part of `1.8.7`

**Comment by clun** [comment]
1.8.7 released
