### ISSUE TITLE
Eventrepository implmentation in ff4j-store-aws-dynamodb

### ISSUE THREAD

**Issue by rahuldaskar** [ff4j/ff4j#418]
If I am not wrong, _ff4j-store-aws-dynamodb_ doesn't have event repository implementation. I see however there is _KeyValueEventRepository_  in ff4j-core module. Will it be useful to configure event repository in DDB?

**Comment by clun** [comment]
AFAIK, Dynamo is a column oriented store. As such it is relevant to store timeseries as long as the row key is well defined (featurename + yyyymmdd ?)

K/V is not really a good implementation I think we can do better to have a proper where clause. But you are right there is no implementation yet.

If you are insterest to implement it I would recommend this one as idea:
https://github.com/ff4j/ff4j/blob/master/ff4j-store-cassandra/src/main/java/org/ff4j/cassandra/store/EventRepositoryCassandra.java

**Comment by rahuldaskar** [comment]
Got it @clun , thanks for the pointer!
