### ISSUE TITLE
FF4j with eureka service registry

### ISSUE THREAD

**Issue by mahwachi** [ff4j/ff4j#419]
is there an update on FF4j to integrate with eureka? as the case with Consul. I'm working on a microservice project and currently we use eureka. thank you

**Comment by clun** [comment]
Hi,

Thank you for opening this ticket. That's a very good reminder. We don't have it yet. It should not be difficult to implement (and doing ETCD at the same time) based on the consul implementation.

SpringCloudEureka is a bit too magic. I will probably ask for an bean of `EurekaClient` in the constructors. (https://github.com/Netflix/eureka/tree/master/eureka-examples_

**Comment by mahwachi** [comment]
thanks clun

**Comment by clun** [comment]
Hello,

I have investigated `Eureka` and unfortunately this framework is 100% a service discovery and does not provide any `store` mechanism on the contrary as Consul (Service Discovery + a K/V Store)

**Design**

Given an Eureka server running, 
- when you "import" a set of features with FF4j in a `EurekaFeatureStore` we will register each feature as a service providing a `vipAdress=feature_name` (using EurekaClient). This vip could have metadata which would be the metadata describing the features. Now you can discover a feature and get the metadata and you evaluate the state - so far so good.

But...
- The Eureka server will  contact component hosting FF4j for health-check as if a feature was a service, which is not, it is just a state.

- Also what happen when you want to update a feature ? You update the Eureka directory. This will be consider as providing a second endpoint for the service/feature and not updating the existing one.

**Decision**

I don't think this is a good idea to store feature states in `Eureka` it has not defined for that. It is simply a list of URL behind an alias to do dynamic load balancing no more.

Even If we could find some tweak with a unique registration of a feature for a service (spof) this is still twisting the framework for something it has not been defined for.

**Comment by mahwachi** [comment]
Hi Clun,

thank you for the clarifications, to be precise, on the project that I work, we use Jhipster Registry which is at once the Eureka server, spring cloud config server that provide runtime configuration to all applications, and an administration server, with dashboards to monitor and manage applications.
I think we are going to use spring cloud config to save feature states.
do you think it will be a good idea?

Thank you.

**Comment by clun** [comment]
I also think the Spring Cloud Config if the one to integrate

**Comment by clun** [comment]
Spring Cloud config does not allowed any extension point to change git by something else I would have to fork. As such I will fork

BTW I am part of the JHIpster dev team and I have created a `ff4j jhipster generator`> I also did a talk on it at JHipster Meetup group.
- https://github.com/ff4j/generator-jhipster-ff4j
- https://www.slideshare.net/CdrickLunven/paris-meetup-jhispter-9-generator-ff4j-for-jhipser

Cheers
