### ISSUE TITLE
insert/update feature/preperty doesn't work with Hikari auto-commit=false

### ISSUE THREAD

**Issue by mahwachi** [ff4j/ff4j#420]
Hi,

I configured FF4j with Hikari and I need to manage the commits in the code and rollback if necessary hence auto-commit = false. but via the ff4j console if I create or modify a feature nothing happens in the database. do i have to change auto-commit = true or is there another way to manage commits with FF4J?

i used FeatureStoreSpringJdbc

in yml file:
 hikari:
      poolName: Hikari
      auto-commit: false

**Comment by clun** [comment]
Multiple ideas.

You can clone this class and change with your own logic: 
https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java

Also for JdbcFeatureStore at some points I explicitly put some `@Transactional` that might explain your issues.
https://github.com/ff4j/ff4j/blob/master/ff4j-store-springjdbc/src/main/java/org/ff4j/springjdbc/store/FeatureStoreSpringJdbc.java#L266

Do you think I should totally get rid of those ? Anyway you can also cone this class and change the annotations, not sure what I can do to allow the Hikari override.

**Comment by mahwachi** [comment]
Hi clun,

thanks for your answer, yes that's what i did, i inherited from the jdbcFeatureStore class and redefine the methods that don't support commit like createproperty. Thank you .
