### ISSUE TITLE
Support Redis Cluster using Lettuce Client 5.x

### ISSUE THREAD

**Issue by ankitjhil** [ff4j/ff4j#421]
We are trying to use the Redis Cluster backing store with FF4J. Defaultly, we are using Lettuce Client 5.3.x but seems like currently FF4J only supports Jedis client to connect to redis.

Is there any way where we can use Lettuce Client with FF4J? Any plans to natively integrate Lettuce?

We are using FF4J 1.8 version.

**Comment by clun** [comment]
You are correct. For now we are using Jedis. We were not aware of Lettuce which seems to intruce nice features and reactive support.

Will investigate what is the effort in terms of code to have dedicated classes or generic ones with 2 possible clients.

**Comment by clun** [comment]
I have implemented the stores with Lettuce. Can you give it a try before release ?

- [FeatureStoreRedisLettuce](https://github.com/ff4j/ff4j/blob/master/ff4j-store-redis/src/main/java/org/ff4j/store/FeatureStoreRedisLettuce.java)
- [PropertyStoreRedisLettuce](https://github.com/ff4j/ff4j/blob/master/ff4j-store-redis/src/main/java/org/ff4j/store/PropertyStoreRedisLettuce.java)
- [EventRepositoryRedisLettuce](https://github.com/ff4j/ff4j/blob/master/ff4j-store-redis/src/main/java/org/ff4j/store/EventRepositoryRedisLettuce.java)
- [FF4jCacheManagerRedisLettuce](https://github.com/ff4j/ff4j/blob/master/ff4j-store-redis/src/main/java/org/ff4j/cache/FF4jCacheManagerRedisLettuce.java)

**Comment by ankitjhil** [comment]
Hi @clun When are you planning to release this feature? Due to very strict timelines at our side, I have not been able to give a chance to test this. Maybe you can plan for the release if you have already fixed it and tested at your side ?

**Comment by Srthak100** [comment]
Hello @clun , any update on this, when you are planning to release this?

**Comment by Srthak100** [comment]
Hi @clun , 
According to your implementation, **RedisClient**(from lettuce 5.x) is used which supports sentinel based redis deployment, but it doesn't support the cluster based redis deployment which is being provided by **RedisClusterClient**(from lettuce 5.x). Are you planning to provide the latter's support too ??

**Comment by clun** [comment]
I simply didn't know there were 2 different version yes.

Will try to add the support immediately

**Comment by ankitjhil** [comment]
@clun When are you planning to release this change?
