### ISSUE TITLE
ff4j rest api did not contains feature status (enable/disable)

### ISSUE THREAD

**Issue by wuhuanxing** [ff4j/ff4j#423]
Hi ff4j, 
I could not found feature status (enabled or disable)from default rest endpoint:   
https://ff4j-demo.herokuapp.com/api/ff4j, just feature list

**Comment by clun** [comment]
Hello, 

You are looking for:
https://ff4j-demo.herokuapp.com/api/ff4j/store/features

Here is a swagger file to help : http://ff4j.org/rest-api/

I will put the swagger/openAPI part in the demo I guess.

Cedrick

**Comment by clun** [comment]
The swagger Documentation is available here : 
https://ff4j-demo.herokuapp.com/swagger-ui.html

_(wait 30s for the app to startup)_

**Comment by wuhuanxing** [comment]
Thanks a lot,  that really help!
