### ISSUE TITLE
is it able to control the visibility of features/properties by Role ?

### ISSUE THREAD

**Issue by wuhuanxing** [ff4j/ff4j#427]
hi ff4j,
I'm trying to make ff4j work with spring security , I follow this sample ( https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-security-spring ) and able to login web console with different users. And now I want to control the visibility of features/properties on web console, how to implement that?

**Comment by clun** [comment]
Hi,

Unfortunately no. The reason is there is no definition of RBAC in a feature. I introduced them in FF4j v2 but this is only alpha stage and there is nothing available to test. Once something is connected he can do everything.

```java
https://github.com/ff4j/ff4j/blob/2.0.RC1/ff4j-core/src/main/java/org/ff4j/core/security/RestrictedAccessObject.java
```

**Comment by wuhuanxing** [comment]
That good news will keep eyes on  FF4j v2 RestrictedAccessObject
