### ISSUE TITLE
Is it possible to connect via some kind of SDK

### ISSUE THREAD

**Issue by ealparslan** [ff4j/ff4j#428]
I am trying to establish a microservices environment with almost 100 microservices using ff4j for my enterprise. I am planning to use PostgreSQL as feature storage. I am planning to have only single management console application.

 As far as I see, all microservices **HAVE TO** connect to the same PostgreSQL database to read features. 

**"Connecting the same database" breaks the microservices architecture**. Is there any better way to do that? Should all my services connect to management service via REST API that ff4j already provides? **Any better way?**

**Comment by drizztguen77** [comment]
We only have 10 microservices and actually implemented it so they look at the same FF4j database for feature flags and their own database for normal data. 

But if you didn't want to do that you could setup FF4j as it's own microservice and implement a check endpoint and then call that check endpoint from your other services. We have implemented a check endpoint that our UI could use but there isn't any reason another microservice couldn't call that same endpoint.

**Comment by ealparslan** [comment]
@drizztguen77 thanks for your clear response.
And yeah that is the solution also in my mind. What is the API response time you are experiencing? Does it work fast? Any insights?

**Comment by drizztguen77** [comment]
I'll have to check Monday to be certain but it's not bad, somewhere in the 75-200ms time I believe.

**Comment by ealparslan** [comment]
that's totally fine @drizztguen77  you don't have to follow that up. At least we have a solution ;) Thank you!
@clun do you think that solution is the best one we have?

**Comment by clun** [comment]
100 microservices hitting the same DB, depending on throughput, could put some pressure on storage like Postgres. (hit ratio). Here are my tough:

1. Having a dedicated storage for feature toggle is recommended for decoupling (dedicated schema in sane DB eventually). In my perspective _Connecting the same database" breaks the microservices architecture._ does not say we need to start an instance of the DB for each micro-services but more ensure isolation (Data Mesh principe) as the DB should have a SPOF -> You can challenge.

2. **Option 1:** Every service connect to the same DB. You could then evaluate dedicated storage for feature toggle like CONSUL. You can also thinkg about the cache layer provided (https://github.com/ff4j/ff4j/wiki/Advanced-Concepts#caching) to limit hit ratio on the DB, distributed cache solution compliant.

3. **Option 2:** Having a dedicated endpoint REST as proposed @drizztguen77 using FeatureStoreHttp (client HTTP). You could also use the cacher layer here. Seems the best way to go.

Finishing the reflection on my end I could think about some graceful degradation. Today if you check for a feature and the DB is not there ff4j throw an exception.... we could have some fallback mechanism either using last value retrieved (store in memory) or returning FALSE.

**Comment by ealparslan** [comment]
@clun do you want me to contribute this feature? I mean I would be more than happy to contribute fallback feature.

**Comment by drizztguen77** [comment]
The way we handled the exception situation that @clun specified is by setting a default value each time we add a new feature flag. That way if it cannot connect to the DB for some reason then it can still run. We have also built in redundancy by providing 2 load balanced instances of our ff4j microservice so if one goes down the other will still take requests.

**Comment by clun** [comment]
Absolutely go for it @ealparslan. 

Constraint is keeping binary compatibility so we could think about a flag (enable fallback) in the ff4j class it self defaulting to false and a try/catch in the check method at top

**Comment by ealparslan** [comment]
We can close this issue
