### ISSUE TITLE
very old version of jquery in ff4j-web causes security issues

### ISSUE THREAD

**Issue by taboubim** [ff4j/ff4j#429]
The actual versions used in the project are : 

- jquery-1.7.2.min.js
- jquery-1.9.1.js
- jquery-1.11.3.min.js

These libraries causes issues while analysing the librairy via sonar...

We propose to updates these versions to use the lastest jquery lib : jquery-3.5.1.min.js

**Comment by clun** [comment]
Sounds like a good plan. Did you try it, can make a PR ?

**Comment by taboubim** [comment]
Yes, I can open a PR... could you give me the rights needed ?

**Comment by taboubim** [comment]
I opened a PR for the issue : https://github.com/ff4j/ff4j/pull/432 ...
Thanks

**Comment by clun** [comment]
UI does not work anymore with 3.5.1, need to investigating
