### ISSUE TITLE
How do we manage separate environments like Prod, preprod etc...

### ISSUE THREAD

**Issue by ealparslan** [ff4j/ff4j#430]
We have a preprod environment and a Prod environment. I could not see any way of defining environment for feature flag. For example I should be able to say feature X should be enabled in preprod but still should be disabled in prod environment.
How I can achieve that? If I have multiple ff4j instances per environment than I need to manually create the same feature flag in each instance right?

**Comment by clun** [comment]
**Recommended:**
This is generally not a good idea to mutualise the storage for feature in multiple environments, we would like to decoupled as much as possible. To move features from one environment to the other you can use the `export` button on the web UI and export as either `XML`, `YAML` or `properties`. Then use `import` still in the UI. You would need 2 console (1 for each environment)

**Mutualization:**
That being said, it is totally doable to mutualise. The idea is to leverage on the  `FlipStrategy`[doc](https://github.com/ff4j/ff4j/wiki/3.-Core-Concepts#flipping-strategy)  and specially `ServerFilterStrategy`.

I think a sample feature defined as XML give you the idea. 
```xml
<feature uid="first" enable="true" description="some desc">
  <flipstrategy class="org.ff4j.strategy.ServerFilterStrategy" >
   <param name="grantedServers">dev01, dev02, dev03</param>
 </flipstrategy>
</feature>
```

Then you need to provide the `serverHostName` in the FF4j context with.
```
FlippingExecutionContext fex = new FlippingExecutionContext();
fex.addValue(ServerFilterStrategy.SERVER_HOSTNAME, "dev01");
ff4j.check(F1, fex);
``` 

Which is true for servename can be adapted for you like `environment`
