### ISSUE TITLE
AuthorizationsManager issue with Ehcache setup

### ISSUE THREAD

**Issue by zengbo0710** [ff4j/ff4j#433]
1. Issue: The Expression of the Feature can't save `&` on UI.

2. Issue: When I use Ehcache and Spring security in my project, the permissions are removed from the Feature when using an unauthorized user, and the modified Feature will be returned from memory in the next call.

Root cause: `AuthorizationsManager` -> `isAllowed` function remove the permission of the Feature, and the modified Feature will be updated to the memory. 

Solution: Override `isAllowed` function, clone the permissions to a new object, use the new object to call `retainAll`.

Could you please fix this issue in `AuthorizationsManager` interface? thanks

**Comment by clun** [comment]
Hello,

Regarding issue 2 I fixed it, duplicating the permission in isAllowed.

Regarding issue 1 I cannot reproduce, it is still the case ?

- Going to https://ff4j-demo.herokuapp.com/ff4j-web-console/features
- Create a new Feature `AAA` and then click CREATE.
- Edit the feature strategy and pick `Expression`
- Change value to `expression=dummy & foo`
- SAVE

Work as expected.
<img width="1233" alt="Screenshot 2020-08-05 at 11 58 56" src="https://user-images.githubusercontent.com/726536/89399743-2696f800-d713-11ea-8a61-d66fe6df6017.png">

**Comment by clun** [comment]
I will stop looking search for 1. Cannot reproduce. Working on a release this week-end

<img width="561" alt="Screenshot 2020-08-07 at 11 55 30" src="https://user-images.githubusercontent.com/726536/89634016-fa12e580-d8a4-11ea-892e-67c9ee09eab6.png">
