### ISSUE TITLE
ff4j-web - doesn't work without trailing slash

### ISSUE THREAD

**Issue by bugs84** [ff4j/ff4j#437]
FF4j Web UI - doesn't work without trailing slash:
https://ff4j-demo.herokuapp.com/ff4j-web-console

Page images and css are not found 
![image](https://user-images.githubusercontent.com/511167/89617308-44d33400-d88a-11ea-84ae-3185161dfe86.png)

This can be fixed by adding the trailing slash
https://ff4j-demo.herokuapp.com/ff4j-web-console/

For sure it is caused by classic issues of servlets with relative paths. The page is looking for resources at URL:
https://ff4j-demo.herokuapp.com/static/img/flags/flagEnglish.png
instead of
https://ff4j-demo.herokuapp.com/ff4j-web-console/static/img/flags/flagEnglish.png

I tried to fix it and provide pull request, but I haven't found elegant solution yet :(

**Comment by clun** [comment]
This is know `issue` yes. Is it painful ?

**Comment by bugs84** [comment]
At first - Thanks for your reply.

It is a little bit painful because members of our team (tens of people) - write URL on their own and when they discover this issue, they are confused/surprised and have a lot of questions :)  . 

But we will be able to live with it. If I find some reasonable solution, I will send Pull Request.  But I remember that this is a pain :)

**Comment by bugs84** [comment]
I suggest this pull request - please check it.
https://github.com/ff4j/ff4j/pull/438

Additional notes: for my project, which is based on sample:
https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-secured-console
I solved it by adding another Servlet mapped exactly on "/ff4jWeb" and this servlet send redirect to "ff4jWeb/".
It works for me, but it is specific for springboot sample. The suggested pull request will solve this issue for everybody.

**Comment by clun** [comment]
PR Accepted, will do a couple of test and release 1.8.8
