### ISSUE TITLE
FF4J - Read Features (Same UId) from multiple Group NOT working

### ISSUE THREAD

**Issue by ckurdekar** [ff4j/ff4j#440]
@clun 

Its strange behaviour, FF4J sometimes able to evaluate features within group, and sometimes getting error feature group doesnot exist.

Tried multiple options
1)ff4j.getFeatureStore().readGroup("groupname").get("featurename").isEnable() - its not consistent behaviour. sometimes able to detect few groups and sometimes not. What could be reason?

2) Can same feature UId present in multiple feature groups?

3)Whats best way to check feature within group? ff4j.check(key) this does works only when 

e.g we have voice and chat as 2 groups, each group has feature called rona.
e.g. voice.rona=true, chat.rona=false... how to specify these featurs? is feature Uid has to be unique across all feature groups or within a feature group?

**Comment by clun** [comment]
1. Group is a property hold by the [feature object](https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/core/Feature.java#L58), meaning there is no "empty" group and the group only exist if a feature hold the property. You can check with `existGroup`. If a group is not found a `GroupNotFoundException` is thrown. You can have list of existing group with `readAllGroups`

If you give me more context ant the implementation of the store you are using I could help you more.

2. **Can same feature UId present in multiple feature groups** : No, for the reason mentioned above, it is a property of the feature itself.

3. **Feature UID has to be unique across all feature groups or within a feature group?** Across all features groups.

I see what you are doing here. Depending on the group you want to enable of not `rona`.

What about a feature called `Rona` and you define a CustomFlipStrategy

```java
public class CategoryFilterStrategy extends AbstractFlipStrategy {

    /** Serial. */
    private static final long serialVersionUID = -485058682902446581L;

    /** Threshold. */
    private static final String ENABLED_GROUPS = "enabledGroups";

    /** Parameter to be checked in context. */
    public static final String CURRENTGROUP = "currentGroup";
    
    /** List of client to be accepted. */
    private static final String SPLITTER = ",";

    /** Validate the target client against the available hostname. */
    private final Set<String> setOfEnabledGroups = new HashSet<String>();

    /**
     * Default Constructor.
     */
    public CategoryFilterStrategy() {}

    public ClientFilterStrategy(String clientList) {
        this.rawClientList = clientList;
        getInitParams().put(PARAM_CLIENTLIST, clientList);
        for (String client : rawClientList.split(SPLITTER)) {
            setOfGrantedClient.add(client.trim());
        }
    }
    
    /** {@inheritDoc} */
    @Override
    public void init(String featureName, Map<String, String> initParams) {
        super.init(featureName, initParams);
        if (initParams != null && initParams.containsKey(ENABLED_GROUPS)) {
           setOfGrantedClient.addAll(initParams.get(ENABLED_GROUPS).split(SPLITTER));
        }
    }
    
    /** {@inheritDoc} */
    @Override
    public boolean evaluate(String featureName, FeatureStore store, FlippingExecutionContext executionContext) {
        if (null == executionContext || !executionContext.containsKey(CURRENTGROUP)) {
            throw new IllegalArgumentException("To work with " + getClass().getName() + " you must provide '"
                    + CURRENTGROUP + "' parameter in execution context");
        }
        return setOfGrantedClient.contains(executionContext.getString(CURRENTGROUP));
    }
}
```

**Comment by ckurdekar** [comment]
> 1. Group is a property hold by the [feature object](https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/core/Feature.java#L58), meaning there is no "empty" group and the group only exist if a feature hold the property. You can check with `existGroup`. If a group is not found a `GroupNotFoundException` is thrown. You can have list of existing group with `readAllGroups`
> 
> If you give me more context ant the implementation of the store you are using I could help you more.
> 
> 1. **Can same feature UId present in multiple feature groups** : No, for the reason mentioned above, it is a property of the feature itself.
> 2. **Feature UID has to be unique across all feature groups or within a feature group?** Across all features groups.
> 
> I see what you are doing here. Depending on the group you want to enable of not `rona`.
> 
> What about a feature called `Rona` and you define a CustomFlipStrategy
> 
> ```java
> public class CategoryFilterStrategy extends AbstractFlipStrategy {
> 
>     /** Serial. */
>     private static final long serialVersionUID = -485058682902446581L;
> 
>     /** Threshold. */
>     private static final String ENABLED_GROUPS = "enabledGroups";
> 
>     /** Parameter to be checked in context. */
>     public static final String CURRENTGROUP = "currentGroup";
>     
>     /** List of client to be accepted. */
>     private static final String SPLITTER = ",";
> 
>     /** Validate the target client against the available hostname. */
>     private final Set<String> setOfEnabledGroups = new HashSet<String>();
> 
>     /**
>      * Default Constructor.
>      */
>     public CategoryFilterStrategy() {}
> 
>     public ClientFilterStrategy(String groupList) {
>         for (String group : groupList.split(SPLITTER)) {
>             setOfGrantedClient.add(group.trim());
>         }
>     }
>     
>     /** {@inheritDoc} */
>     @Override
>     public void init(String featureName, Map<String, String> initParams) {
>         super.init(featureName, initParams);
>         if (initParams != null && initParams.containsKey(ENABLED_GROUPS)) {
>            setOfEnabledGroups.addAll(initParams.get(ENABLED_GROUPS).split(SPLITTER));
>         }
>     }
>     
>     /** {@inheritDoc} */
>     @Override
>     public boolean evaluate(String featureName, FeatureStore store, FlippingExecutionContext executionContext) {
>         if (null == executionContext || !executionContext.containsKey(CURRENTGROUP)) {
>             throw new IllegalArgumentException("To work with " + getClass().getName() + " you must provide '"
>                     + CURRENTGROUP + "' parameter in execution context");
>         }
>         return setOfEnabledGroups.contains(executionContext.getString(CURRENTGROUP));
>     }
> }
> ```
> 
> The class [ClientFilterStrategy](https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/strategy/ClientFilterStrategy.java) works a bit like that. Hope it helps.

For Point 1. ) even Group "groupname" is present in feature xml, only same feature UId  "featurename" was used in multiple feature group. Is that the reason Ff4j was able to work ff4j.getFeatureStore().readGroup("groupname").get("featurename").isEnable()... this was working for few attempts and after executing ff4j.getFeatureStore().readGroup("groupname2").get("featurename").isEnable()...ff4j was not working for ff4j.getFeatureStore().readGroup("groupname").get("featurename").isEnable().... something is wrong ... 

But i guess the term feature group i was under different impression like feature group-->feature (0-n) relation ship..so that i can define 2 level hierarchy

**Comment by clun** [comment]
I understand the confusion, it is not really a hierarchy only a property.

For V2 maybe I should add this 2 levels or even X levels.
