### ISSUE TITLE
Is is possible to send ff4j audit events to external system asynchronouly (sqs, kafka...) 

### ISSUE THREAD

**Issue by rafaelbarbiero** [ff4j/ff4j#442]

**Comment by clun** [comment]
Can you tell me more about this ?

When a feature is toggled you wan to send an event to external system like kafka ? We could do that implementing a KafkaEventRepository implementing `saveEvent()` and let read method empty. Or event a PROXY on top of EventRepository. Does it fits your needs ?

NB: In V2 you will register some listerner on repository making easier to create events.

**Comment by rafaelbarbiero** [comment]
Hi @clun. It will fit my needs. I didn't know about this feature. Thank so much for answer!

**Comment by clun** [comment]
I can help you implementing this.  in V1 we still need to create this code to send to Kafka or any external source. Which system so you target Kafka ? Prometheus ?

**Comment by rafaelbarbiero** [comment]
Thank you for help! I am thinking about use this framework to configure all the properties to whole micros services ecosystem. Actually we don't use Kafka, but we are using SNS+SQS to publish all events as an event stream. Can you tell if i can use only single instance of FF4J to manage features to multiple micro services at the same time?

**Comment by clun** [comment]
> use this framework to configure all the properties to whole micros services ecosystem.

Yes you can do this.

You have a dedicated component for FF4j web-console + FF4j REST API. You can use almost this one only change the stores : https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-secured-console. You should have multiple instances to avoid being a SPOF with a load balancer.

**Option A:**
In all others microservices are using the `PropertyHttpStore` (that will point to the REST API). This way the databases configuration is defined only in the component described above. That's simply how you handle the configuration. You may think that you will have a bad latency if each time you need to do an HTTP call and you are right. To avoid this in the microservices you can setup some cache either in memory or redis.

**Option B:**
In all others microservices you set FF4j to point to the same DB as the component with the we console and you have a sample here : https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-1x/ff4j-voxxeddays-ticino-2018

Associated video : https://www.youtube.com/watch?v=P6PtQtOYhus

----
> SNS+SQS to publish all events as an event stream.

Seems like this is the properties that you are interested in (PropertyStore). FF4j is quite open and we can imagine a lot of things to extends the feature.

Looking at the interface:
https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/property/store/PropertyStore.java

What about a proxy that would trigger and event `onSaveProperty` and `onUpdateProperty` ? will see If I can backport the listerner mechanism in V1 tomorrow

**Comment by clun** [comment]
When audit is set to `true` in the `FF4j` object soem proxies are already created calling an eventPublisher that put some sameEvent in an executor. For the async part we are cover.

The easier way is probably to override the `saveEvent` in your own repository. Here is a code proposition did not try it myself but with that no change at ff4j level.

```java
import org.ff4j.audit.Event;
import org.ff4j.audit.repository.InMemoryEventRepository;

import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.SendMessageRequest;

/**
 * Overriding async saveEvent to log to external system as well
 */
public class EventRepositoryObserverSqs extends InMemoryEventRepository {
    
    private AmazonSQS sqs;

    private String queueUrl;
    
    /**
     * Provide same constructor
     */
    public EventRepositoryObserverSqs(Integer capacity, AmazonSQS sqs, String queueUrl) {
        super(capacity);
        sqs                  = sqs;
        this.queueUrl = queueUrl;
    }
    
    /**
     * Overriding Event Repository to publish event on external system as well.
     * saveEvent is already invoked in asynchronous way so there you can simply override.
     */
    @Override
    public boolean saveEvent(Event e) {
        boolean parent = super.saveEvent(e);
        if (parent) {
            // Push to SQS
            SendMessageRequest send_msg_request = new SendMessageRequest()
                    .withQueueUrl(queueUrl)
                    .withMessageBody(e.toJson())
                    .withDelaySeconds(5);
            sqs.sendMessage(send_msg_request);
        }
        return parent;
    }

}
```

and then

```java
AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();
// [...]

FF4j ff4j = new FF4j();
ff4j.setPropertiesStore(new InMemoryPropertyStore("ff4j.xml"));
ff4j.setEventRepository(
  new EventRepositoryObserverSqs(10, sqs, 
      "https://sqs.eu-west-1.amazonaws.com/54XXXXXXX57/serversncodeq"));
ff4j.audit(true);

```

**Comment by rafaelbarbiero** [comment]
Thank you @clun.

**Comment by clun** [comment]
As answered, will close it for now. Don't hesitate to reopen is issue.
