### ISSUE TITLE
Redis key prefix

### ISSUE THREAD

**Issue by pedroxs** [ff4j/ff4j#443]
Currently when using Redis as a storage solution the keys are prefixed with `FF4J_` as documented on the [wiki](https://github.com/ff4j/ff4j/wiki/Store-Technologies#redis).

I would like to be able to redefine this prefix, currently this is a hard coded configuration, so not possible. Or at the very least be able to add a pre-prefix, for example if I want to share more then one project with the same Redis instance and be sure there will be no conflicts.

**Comment by clun** [comment]
That's legit let me adapt the store.

**Comment by clun** [comment]
Evolution has been implemented. The stores have a new constructor having a `RedisKeysBuilder`

```java
RedisKeysBuilder keyBuilders = new RedisKeysBuilder("prefix");
FeatureStoreRedis redisStore = new FeatureStoreRedis(redisConnection, keyBuilders);
```

should be part of 1.8.9 this week
