### ISSUE TITLE
Two level caching at client side

### ISSUE THREAD

**Issue by Srthak100** [ff4j/ff4j#444]
**CURRENT ARCHITECHTURE**: According to our current system we have a separate ff4j-web application in which the capability of reading feature from redis and from the DB is maintained. Also we have a ff4j-client which is provided in form of a jar to client services. This ff4j-client jar contains one level caching or the InMemoryCache which is being accessed and read before making a http call to ff4j-web application.

**OUR APPROACH**: We wanted to have a two level cache at client side or in the ff4j-client jar. That means basically first the feature will be read from in-memory cache, if the value is null then it goes to redis(basically which was used by ff4j-web application to set the features and properties), then go for the http call if the value from redis was also null.

**IMPLEMENTATION**: We were thinking of making our own implementation of FF4JCacheManager which would extend InMemoryCacheManager. In this we would override the methods.

Any suggestion or advice on how can we do it. Or is this approach/idea correct to be implemented.

**Comment by clun** [comment]
Hi,
Implementing you own cache manager is one way to do it yes. 

Now:
- The CacheProxy itself implements Implement FeatureStore and PropertyStore
- FF4j provide a Redis CacheManager

Not sure if would match your requirements but you can try to chain the cache proxies.

```java
FF4j ff4j = new FF4j();
FeatureStore  httpFStore = new FeatureStoreHttp();
PropertyStore httpPStore = new PropertyStoreHttp();

// Cache 2
FF4JCacheManager cache2Redis = new FF4jCacheManagerRedisLettuce();
FF4jCacheProxy cp2 = new FF4jCacheProxy(httpFStore, httpPStore, cache2Redis);

// Cache 1 
FF4JCacheManager cache1Memory = new InMemoryCacheManager();
FF4jCacheProxy cp1 = new FF4jCacheProxy(cp2, cp2, cache1Memory);

ff4j.setFeatureStore(cp2);
ff4j.setPropertiesStore(cp2);
```

**Comment by Srthak100** [comment]
Thank you for the suggestion will try this approach.

**Comment by clun** [comment]
Evolution has been implemented:
- If an error occured at cache level, no error will appear in the logs or anythin.

If you want to change this behaviour you can create your own specialized class:

```java
public class CustomHandleExceptionCacheManager extends AnExistingCacheManager {
    
    @Override
    public void onException(Throwable error) {
       // do something
    }

}
```

**Comment by clun** [comment]
`1.8.9` is out with this evolution. Open a ticket if issue

**Comment by Srthak100** [comment]
@clun Thanks for the active support.
