### ISSUE TITLE
Issue with case-insensitive DBs using PropertyStoreSpringJdbc

### ISSUE THREAD

**Issue by pedrompg** [ff4j/ff4j#446]
Hi everyone, 

I am working on creating a service using Spring Boot + FF4J + Postgres as database and I ran into this issue since Postgres is by default case insensitive. The string used to create the table is `FF4J_PROPERTIES` which ends up creating a table called `ff4j_properties` on Postgres. When checking for the table being present using the uppercase string, it is not found, leading to the `createSchema` method trying to recreate the table, which causes an exception.

You can see the error being reproduced in this [sample class]( https://github.com/pedrompg/ff4j-spring-boot/blob/master/src/test/java/com/github/pedrompg/ff4j/ApplicationIntegrationTest.java) (you can execute the tests using `./gradlew test)`

I've tracked the issue on the code [PropertyStoreSpringJdbc.java#L216](https://github.com/ff4j/ff4j/blob/master/ff4j-store-springjdbc/src/main/java/org/ff4j/springjdbc/store/PropertyStoreSpringJdbc.java#L216) as the class uses its own method to figure out if a table exists instead of [JdbcUtils.java#L66](https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/utils/JdbcUtils.java#L66) which handles the problem correctly

I would be happy to open an MR to fix the issue. Only question about this would be how to add the tests to cover this, since it is not reproducible using HSQL or H2. 

Any guidance is appreciated :)

**Comment by clun** [comment]
Hi,

Thank you for considering helping, always welcomed.

To implement it I would advice you to create a new unit test using [testContainers](https://www.testcontainers.org/). A container is started with the unit test to test against a dedicated db.

Here is a sample for Cassandra:
https://github.com/ff4j/ff4j/blob/master/ff4j-store-cassandra/src/test/java/org/ff4j/cassandra/docker/FeatureStoreCassandraTestDocker.java

**Comment by pedrompg** [comment]
Awesome i didn't know TestContainers was already being used in other modules. I will try to create the PR today with the changes
