### ISSUE TITLE
How to setup Admin console with Spring Boot ?

### ISSUE THREAD

**Issue by chtnazareth** [ff4j/ff4j#453]
Spring boot version:  (v2.1.3.RELEASE)
FF4J version: 1.8.9

Using those versions seems that I have problems reading static content for the web console... Page opens but not is working..

In Log I have : TRACE [099-exec-1] o.s.w.s.r.ResourceUrlEncodingFilter                          : ResourceUrlProvider not available via request attribute ResourceUrlProviderExposingInterceptor.RESOURCE_URL_PROVIDER_ATTR

I have tried several configurations.
My config:

@Configuration
@ConditionalOnClass({ FF4jDispatcherServlet.class})
@AutoConfigureAfter(FF4jConfig.class)
@ConditionalOnProperty(value="ff4j.webconsole.enable", havingValue = "true", matchIfMissing = false)
public class FF4jWebConsoleConfig {

    @Value("${ff4j.webconsole.url:/ff4j-web-console}")
    private String webConsoleUrl;

    @Bean
    @ConditionalOnMissingBean
    public FF4jDispatcherServlet getFF4jDispatcherServlet(FF4j ff4j) {
        FF4jDispatcherServlet ff4jConsoleServlet = new FF4jDispatcherServlet();
        ff4jConsoleServlet.setFf4j(ff4j);
        return ff4jConsoleServlet;
    }

    @Bean
    @SuppressWarnings({"rawtypes","unchecked"})
    public ServletRegistrationBean ff4jDispatcherServletRegistrationBean(FF4jDispatcherServlet ff4jDispatcherServlet) {
        return new ServletRegistrationBean(ff4jDispatcherServlet, webConsoleUrl + "/*");
    }

}

**Comment by clun** [comment]
Here is a working sample updated in `1.8.9`
https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-springboot2x
