### ISSUE TITLE
Vulnerable JQuery version in FF4J Web

### ISSUE THREAD

**Issue by YuriMB** [ff4j/ff4j#464]
There is a reference to JQuery 1.9.1 in view-header.html:

https://github.com/ff4j/ff4j/blob/901ec1c7feade1bbc2c3bd42dbf7eb27ddee8097/ff4j-web/src/main/resources/views/view-header.html

There are known CVE's for this version of JQuery:
![image](https://user-images.githubusercontent.com/5307440/95174183-01c60c00-07ba-11eb-970c-c2ed6d384557.png)

**Comment by clun** [comment]
We are aware but we don't have skills to migrate to jQuery 3.5.x can you have a look ?
