### ISSUE TITLE
Ff4j read propery/custom property from rest api(http://ff4j.org/rest-api/) 

### ISSUE THREAD

**Issue by mageshbabu-spg** [ff4j/ff4j#469]
Hi,
is there any way to read the property values from rest api as like feature enable or not?

eg: username : cedrick
any way to read the property value like /api/store/{username}

likewise for properties in feature

API doc:http://ff4j.org/rest-api/

**Comment by clun** [comment]
Hi sorry for delay in reponse

This is the URL you are looking for `https://ff4j-demo.herokuapp.com/api/ff4j/propertyStore/properties/username`

The swagger you point is out of date, I need to update it.

Will keep the issue open to create a working sample and update the doc

**Comment by clun** [comment]
I updated the sample here you can now have a full swagger UI with all method to test, better than some doc 
https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-springboot2x
