### ISSUE TITLE
FF4J UI breaks most of the time

### ISSUE THREAD

**Issue by Srthak100** [ff4j/ff4j#470]
We are facing this issue from a long time now, whenever i try to open the ff4j-web-console the UI gets distorted after opening the features page, and when i refresh the page it redirects me to error page as shown below.

![image](https://user-images.githubusercontent.com/31232515/95838026-ed0bea00-0d5e-11eb-9960-d66ff47ac367.png)
We are using google Oauth v2 and also we have ff4j deployed on several enviornments but this issue is coming only on one env. 
@clun Can you please help here or guide what can be the issue here.

**Comment by clun** [comment]
? 

There is no OAuth2 in FF4j what so ever. I bet this is due to the spring security filter configuration you put in place at your location.

Do you have an error stack message to share ? A spring security config file maybe ?
