### ISSUE TITLE
Create a release with security fixes?

### ISSUE THREAD

**Issue by YuriMB** [ff4j/ff4j#477]
Is it possible to create a new release and upload it to mvncentral which contains the latest jquery version? The current versions block our ability to create a new productionrelease.
If not, could you tell me the releasecycle?

**Comment by clun** [comment]
Hello Yuri,

Yes this is possible. I will to it later today `11/5` fixing a special char bug ATM

**Comment by clun** [comment]
`1.8.11` is out will close this for now
