### ISSUE TITLE
Initialise features from environment variables or properties file

### ISSUE THREAD

**Issue by DerrylThomas** [ff4j/ff4j#479]
Hello,

I have a use case I am trying to implement and would like any suggestions. 

I have a couple of feature flags that I will provide as environment variables (by providing it in the k8s yaml during deployment).  For example:
ENABLE_FEATURE_1=true
ENABLE_FEATURE_2=false

I want to be able to initialise the feature store based on these environment variables. For example, I want to disable feature1 in my prod environment and enable it in my pre-prod environment. 

One way I could think of is to read this feature flag in the application.properties file. Something like this:
feature.toggles.enable_feature_1=${ENABLE_FEATURE_1:false}
feature.toggles.enable_feature_2=${ENABLE_FEATURE_2:false}
And then somehow initialise the feature store based on these property values. 

Is my approach sensible? Or is there an easier/better way to achieve this use case?
I would really appreciate any help you can afford.

**Comment by demousermkt** [comment]
@clun, thanks a ton! This seems perfect :)

**Comment by DerrylThomas** [comment]
@clun , thanks a ton! This seems perfect :)
