### ISSUE TITLE
Backward compatibility with the Jedis version upgradation

### ISSUE THREAD

**Issue by Srthak100** [ff4j/ff4j#480]
As we are currently using version 1.8 for all the ff4j-packages including ff4j-store-redis. That includes a class file Pool.class which resides in the package: redis.clients.util.Pool and if we will upgrade to the latest of ff4j version this class package changes to : redis.clients.jedis.util.Pool. This is because the jedis version is upgraded.
@clun can you please help here to make it backward compatible.

**Comment by clun** [comment]
Hello sir,

The interfaces did not change so you can stick to previous version of `ff4j-store-redis` and upgrade the rest.

```xml
 <properties>
    	<ff4j.version>1.8.11</ff4j.version>
</properties>

<dependencies>
        <dependency>
            <groupId>org.ff4j</groupId>
            <artifactId>ff4j-spring-boot-starter</artifactId>
            <version>${ff4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.ff4j</groupId>
            <artifactId>ff4j-store-redis</artifactId>
           <version>1.8.1.</version>
        </dependency>
         <dependency>
            <groupId>org.ff4j</groupId>
            <artifactId>ff4j-web</artifactId>
           <version>${ff4j.version}</version>
        </dependency>
    </dependencies>
```
