### ISSUE TITLE
Trying to connect to  http://f4j-demo.herokuapp.com/api/ff4j from springboot project and not able to connect

### ISSUE THREAD

**Issue by loukyap** [ff4j/ff4j#483]
@clun  Could you please help me show the sample project that consumes these apis. I tried with http and https both and I am not able to connect through my java code.

**Comment by loukyap** [comment]
Receiving connection timeout

**Comment by clun** [comment]
Absolutely:
- Live demo : https://ff4j-demo.herokuapp.com/
- Swagger (client UI) : https://ff4j-demo.herokuapp.com/swagger-ui/
- API URL : https://ff4j-demo.herokuapp.com/api/ff4j
- Code of the demo app : https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-springboot2x

Now you want to connect there with a client that consumes the API:
- Here is the code : https://github.com/ff4j/ff4j-samples/tree/master/ff4j-sample-client

**Comment by clun** [comment]
Will close for now you can work with the sample above.
