### ISSUE TITLE
How to programmatically consume Spring MVC Rest API on Client Side and Cache suggestions?

### ISSUE THREAD

**Issue by sunnyrockstar98** [ff4j/ff4j#485]
Hi @clun 

I have exposed the **SpringMVC** _(I have not used Jersey implementations)_ implementation of the REST API on the server component which holds - Web Console+ REST API+ DB connection. I have other Java(Spring) based microservices(clients) where I just want to call the REST API.

I am currently using **RestTemplate** to make calls to the api like this - 

            String url = "https://***-dev-us-c-apim.azure-api.net/ff4j-feature-toggle-server/api/ff4j/check/dummy";
            Boolean results = restTemplate.getForObject(url, Boolean.class);

 But is there a way to programmatically consume the api on client side?

All I could find on the docs - https://github.com/ff4j/ff4j/wiki/Web-Concepts#securing-accesses-to-api
But I guess this is for Jersey implementation. How to consume like this if I have exposed the REST API in SpringMVC style?

**Comment by clun** [comment]
Hi @sunnyrockstar98, 

Absolutely, i don't expect you to consume resources with a Rest Template and the swagger documentation.

It may sounds weird but you need to import `ff4j-webapi-jersey2x`.

There you can use [FeatureStoreHttp](https://github.com/ff4j/ff4j/blob/master/ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/jersey2/store/FeatureStoreHttp.java)

I would also invite you to wrap this store with a cache at client side.
https://github.com/ff4j/ff4j-samples/tree/master/ff4j-sample-client

```java
String ff4jApiEndPoint = "https://ff4j-demo.herokuapp.com/api/ff4j";
FeatureStoreHttp  fStore = new FeatureStoreHttp(ff4jApiEndPoint);
PropertyStoreHttp pStore = new PropertyStoreHttp(ff4jApiEndPoint);
/** 
 * Maybe we don't want to do an http call each time we test a feature
 *  as there is latency. Local in memory cache with TTL 10min can help.
 */
FF4jCacheProxy cc = new FF4jCacheProxy(fStore, pStore, new InMemoryCacheManager(600));

ff4j = new FF4j();
ff4j.setFeatureStore(cc);
ff4j.setPropertiesStore(cc);
```

**Comment by sunnyrockstar98** [comment]
Hey Thanks for this @clun .
This works.

But there is one issue I was getting when running Jersey API in TOMCAT - 

`java.lang.IllegalStateException: InjectionManagerFactory not found.`

Found the solution - [https://stackoverflow.com/a/44546979](url)

Just for others who try this - in addition to **ff4j-webapi-jersey2x** we need to add this dependency as well - 

`        

        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>2.29.1</version>
        </dependency>`


And @clun thanks for this suggestion

> cache at client side.

**Comment by sunnyrockstar98** [comment]
@clun  I was looking for some advice for **server-triggered client-side caching** for this particular scenario - If I implement the cache in this manner with a certain TTL and at the same time on the server side the toggle is flipped I will be presenting stale toggle value to the client-side as it will continue to serve the old toggle value.

I was looking for a client-side cache implementation where if the toggle value is changed on the server component that would trigger a client-cache refresh/notification or something so that I can avoid the **Stale Toggle Issue.**

Any suggestions??

**Comment by clun** [comment]
In the current cache client implementation we do have a polling mechanism.

Solution would be to have the observer pattern. When data is updated a notification is sent through a topic and client subscribe to the topic. This is what have been designed for V2. Also you can implement your with FeatureCacheProxy and CacheManager.

**Comment by sunnyrockstar98** [comment]
This observer pattern is coming in V2?

**Comment by clun** [comment]
I will close this issue with a `V2` tag. I had the in-memory store working for `v2` but not sure if i expect a release.
