### ISSUE TITLE
Unable to use FF4jProvider for web console as documented here: https://github.com/ff4j/ff4j/wiki/Web-Concepts#web-console

### ISSUE THREAD

**Issue by franden** [ff4j/ff4j#486]
I am trying to use ff4j web console in our project. therefore I checked documentation and some examples (https://github.com/ff4j/ff4j-samples/tree/master/webapp-jetty/ff4j-sample-web), but unfortunately I get an exception if the  FF4jDispatcherServlet tries to get Instance of my FF4jProvider. 
```
Caused by: java.lang.NoSuchMethodException: org.ff4j.sample.SimpleFF4jProvider.getInstance()
    at java.lang.Class.getMethod (Class.java:2108)
    at org.ff4j.web.FF4jServlet.initializeFF4J (FF4jServlet.java:153)
    at org.ff4j.web.FF4jServlet.init (FF4jServlet.java:112)
...
```
The cause of this issue is this commit: https://github.com/ff4j/ff4j/commit/d9584eb7aa14b50dbcdf6826e5587e4e87915ede#diff-ae79b5b13181ccd929d0b086cf0b4b5e6a6fff8c9987908186e1dafc076f4b65

This line must be fixed:
https://github.com/ff4j/ff4j/blob/f3c07b49deabd04caef8b0f3a491ab3ae514ca36/ff4j-web/src/main/java/org/ff4j/web/FF4jServlet.java#L153

**Comment by clun** [comment]
As of now you need to implement the `getInstance()` method.

```java
public static synchronized SimpleFF4jProvider getInstance() { 
   return new SimpleFF4jProvider(); 
}
```
