### ISSUE TITLE
edit Fixed Values for Properties error happen

### ISSUE THREAD

**Issue by YYYY-MM-DD** [ff4j/ff4j#488]

**Comment by YYYY-MM-DD** [comment]
1、[New+]   save a new property
2、Eidt the property adding at  setp 1
3、[+] add a Fixed Values that not equals the Value
4、[Valid]
5、Error happen and the Properties can’t be used any more

**Comment by clun** [comment]
When this happen you change the value to property using to the fixed Values using the drop down :

Reproducing the situation 
<img width="556" alt="Screenshot 2022-12-19 at 23 08 19" src="https://user-images.githubusercontent.com/726536/208536115-42a69d4d-8c57-469a-aeab-c557149e943c.png">

Changing value
<img width="555" alt="Screenshot 2022-12-19 at 23 08 26" src="https://user-images.githubusercontent.com/726536/208536185-6e76f805-b4c6-4ac9-a018-402a076f29ff.png">

Updated Value
<img width="1234" alt="Screenshot 2022-12-19 at 23 10 47" src="https://user-images.githubusercontent.com/726536/208536409-6e89dbad-e28b-406c-9d25-44c475d862ff.png">
