### ISSUE TITLE
Do not create session in web console

### ISSUE THREAD

**Issue by bjab** [ff4j/ff4j#490]
I think that forcing session creation here is unnecessary. When combined with spring secruity, session creation in some cases it will render all links with `;jsessionid=...` and spring will reject those links as security breach (`The request was rejected because the URL contained a potentially malicious String ";"`)

You can obtain servletContext by `request.getServletContext()` call

https://github.com/ff4j/ff4j/blob/a31cb8caf8b8c4874fcd6bb64893f4f50919af3c/ff4j-web/src/main/java/org/ff4j/web/controller/AbstractController.java#L159
https://github.com/ff4j/ff4j/blob/a31cb8caf8b8c4874fcd6bb64893f4f50919af3c/ff4j-web/src/main/java/org/ff4j/web/controller/AbstractController.java#L204

**Comment by clun** [comment]
This is maybe relevant but the library can also be used in a web application WITHOUT spring :) (jersey2x).
