### ISSUE TITLE
Does ff4j support pub/sub model?

### ISSUE THREAD

**Issue by Srthak100** [ff4j/ff4j#494]
**Question**
There is a requirement where we want a pub/sub model in ff4j. Whenever a update operation is performed on a feature on server side there is an event fired(published) which is being subscribed by the client. Doses ff4j have a functionality like this?
@clun Please help on this.

**Comment by clun** [comment]
It is not provided out of the box yet.

To implement it, it is simple. You need a single class extending your `EventRepository` sending events to the broker of your choice. Here a sample for Amazon SNS => https://github.com/ff4j/ff4j/issues/442

**Comment by Srthak100** [comment]
Thanks clun will have a look at it.
