### ISSUE TITLE
Support for clients in other languages?

### ISSUE THREAD

**Issue by checketts** [ff4j/ff4j#497]
Is there support for .Net or Node.js clients? If not would there be interest in pull requests to support those?

**Comment by clun** [comment]
Hello,

As of today we do not have clients for the REST API no. Yes we would be interested to have nodeJS client for sure and also for .NET

**Comment by checketts** [comment]
I would like to propose adding RESTful endpoints that support the Unleash SDKs (https://github.com/Unleash/unleash#client-implementations)

If that approach is acceptable then I'll begin investigating the extensibility options.

**Comment by clun** [comment]
Please proceed, no blocking here

**Comment by clun** [comment]
Any updates here ? if not no issue i would simply close the ticket.

**Comment by checketts** [comment]
Go ahead an close this.
