### ISSUE TITLE
Event repository with DynamoDB

### ISSUE THREAD

**Issue by Srthak100** [ff4j/ff4j#499]
Hi @clun,
We are about to use DynamoDB for the feature and property store, but we also need an event repository like **EventRepositorySpringJdbc**. Can you please clarify if there is any available repository with DynamoDB, there is no such class in the module **ff4j-store-aws-dynamodb**.

**Comment by clun** [comment]
Hello,

As of today there is no implementation for `EventRepository` fro DynamoDB. The contributor only did Features and Properties. We would accept pull requests.

As far as I know, It is not easy to store timeseries in a Dynamo yet you can leverage on implementations of REDIS or CASSANDRA to implement with Dynamo.

**Comment by Srthak100** [comment]
Okk thanks for the clarity over this. As of now our requirement have changed and opted for MySQL instead of Dynamo.
