### ISSUE TITLE
Postgre Started for Spring Boot 2 is throwing bad grammer error

### ISSUE THREAD

**Issue by agenttuy** [ff4j/ff4j#502]
PreparedStatementCallback; bad SQL grammar [SELECT COUNT(FEAT_UID) FROM FF4J_FEATURES WHERE FEAT_UID = ?]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "ff4j_features" does not exist
  Position: 29

Using posgre vesrion 12.7 with spring boot 2.. any ideas?

**Comment by agenttuy** [comment]
Run the DDL mentioned here, https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/main/resources/schema-ddl.sql, see a different error now.. 

Caused by: org.postgresql.util.PSQLException: ERROR: column "feat_uid" does not exist
  Position: 14

**Comment by agenttuy** [comment]
Oh, i got it to work, seems the solution was to update the DDL to ALL lowercase... this worked. Seems there is a disconnect between the app and the DDL.

-- Main Table to store Features
CREATE TABLE FF4J_FEATURES (
  "feat_uid"     	VARCHAR(100),
  "enable"  		INTEGER NOT NULL,
  "description" 	VARCHAR(1000),
  "strategy"		VARCHAR(1000),
  "expression"	    VARCHAR(255),
  "groupname"		VARCHAR(100),
  PRIMARY KEY("feat_uid")
);

-- Roles to store ACL, FK to main table
CREATE TABLE FF4J_ROLES (
  "feat_uid"     VARCHAR(100) REFERENCES FF4J_FEATURES("feat_uid"),
  "role_name"    VARCHAR(100),
  PRIMARY KEY("feat_uid", "role_name")
);

-- Feature Internal Custom Properties
CREATE TABLE FF4J_CUSTOM_PROPERTIES (
  "property_id"  VARCHAR(100) NOT NULL,
  "clazz" 		 VARCHAR(255) NOT NULL,
  "currentvalue" VARCHAR(255),
  "fixedvalues"	 VARCHAR(1000),
  "description"	 VARCHAR(1000),
  "feat_uid"     VARCHAR(100) REFERENCES FF4J_FEATURES("feat_uid"),
  PRIMARY KEY("property_id", "feat_uid")
);

-- @PropertyStore (edit general properties)
CREATE TABLE FF4J_PROPERTIES (
  "property_id"  VARCHAR(100) NOT NULL,
  "clazz" 		 VARCHAR(255) NOT NULL,
  "currentvalue" VARCHAR(255),
  "fixedvalues"	 VARCHAR(1000),
  "description"	 VARCHAR(1000),
  PRIMARY KEY("property_id")
);

-- @see JdbcEventRepository (audit event)
CREATE TABLE FF4J_AUDIT (
  "evt_uuid" 	 VARCHAR(40)  NOT NULL,
  "evt_time" 	 TIMESTAMP 	  NOT NULL,
  "evt_type" 	 VARCHAR(30)  NOT NULL,
  "evt_name" 	 VARCHAR(100)  NOT NULL,
  "evt_action" 	 VARCHAR(100)  NOT NULL,
  "evt_hostname" VARCHAR(100)  NOT NULL,
  "evt_source" 	 VARCHAR(30)  NOT NULL,
  "evt_duration" INTEGER,
  "evt_user" 	 VARCHAR(30),
  "evt_value" 	 VARCHAR(100),
  "evt_keys" 	 VARCHAR(255),
  PRIMARY KEY("evt_uuid", "evt_time")
);

**Comment by drizztguen77** [comment]
Actually it depends on how the database is configured. It sounds as though your database is configured for case sensitivity. So yes, if your database is case sensitive for table names then you would need to make them all lowercase. If the database is set to not be case sensitive then the DDL would work fine as it is.
