### ISSUE TITLE
Admin console - styling

### ISSUE THREAD

**Issue by mojo2012** [ff4j/ff4j#506]
Hi everybody,

is is possible to change the styling of the administration console through some config properties, especially the font and colors?

If not, it would be nice to have at least a basic styling ability.

Cheery, Matti

**Comment by clun** [comment]
Hello Mojo,

The files to edit are 
- https://github.com/ff4j/ff4j/blob/master/ff4j-web/src/main/resources/ff4j-embedded.css
- https://github.com/ff4j/ff4j/tree/master/ff4j-web/src/main/resources/views

From there build your version of ff4j-web and you are good to go

**Comment by psoch** [comment]
Adding a custom `style.css` file to `src/main/resources/static/css/` overrides the admin console's styling.
