### ISSUE TITLE
Enquiry :  Is it possible to use this library for values required at application startup for a plain java application

### ISSUE THREAD

**Issue by anilkumarmalipatil** [ff4j/ff4j#508]
Hello Team, 

I am exploring this library to be used for a Toggling feature use case. Is it possible to use this with a plain java application to store values required at the application start up.

**Comment by clun** [comment]
Hello Anil,

Yes you can. `ff4j-core` requires NO dependency at all. Values of can be in a database or in a file (XML, YAML,PROPERTIES).

Now to have the web console and edit values at runtime you need some dependencies like spring
