### ISSUE TITLE
What is the intended way of using feature monitoring with FeatureStoreHttp?

### ISSUE THREAD

**Issue by gpr-indevelopment** [ff4j/ff4j#516]
My team is beggining to run a microservices architecture and we plan on start using feature flags with FF4J. We have deployed a spring boot service with FF4J starter connected to a MySQL database feature persistence - This is our features server. We intend on using the FF4J web API client library on our Java services for checking features from our features server.

But, we noticed that checking features via FeatureStoreHttp (available on the web API client library) does not fire the "checkOn" event on the features server. That happens because `FF4j` from `ff4j-core` requests a `Feature` object from the REST API from the server, and checks its `enable` boolean field. This request does not fire the "checkOn" event.

Fires "checkOn" event, and is not used by the web API client: 
> GET /api/ff4j/check/{uid}

Does not fire "checkOn" event, and its used by the web API client: 
> GET /api/ff4j/store/features/{uid}

I noticed that the `FF4j` class fires the "checkOn" event from the client to a `InMemoryEventRepository` by default. Apparently there is not an implementation of `EventRepository` that is able to push this event to the features server. Also, I couldnt find an endpoint on the features server for me to push events to. It would be ideal for us to monitor the features from a centralized dashboard, such as the feature server's.

What is the intended way of working with FF4J's feature monitoring on a microservices architecture? It seems the events are only available (by default) in memory on the services, and I dont want to couple all my services to a SQL database just for event persistence.

Client library: 
```xml
<dependency>
    <groupId>org.ff4j</groupId>
    <artifactId>ff4j-webapi-jersey2x</artifactId>
    <version>1.8.11</version>
</dependency>
```

**Comment by clun** [comment]
Hi,

First you have the good architecture:
- A backend connected to the store (here mysql), and exposing the REST HTTP API
- Multiple services requesting the rest API to get the status of the feature.

When you want to evaluate if a feature is toggled (or not) the idea was to use. This one should trigger the `checkOn` event.
> `GET /api/ff4j/check/{uid}`

The second service you are referring to is there to retrieve a feature and load its attributes. This service is costly as it will induce a marshaling of the `Feature` bean that is not mandatory.

`EventRepository` got multiple implementations (in 20 stores, about 10 have the implementation) but for some, its does make sense, it does not match the use cases of such a database or simply we did not find a way to do it. Let me give you a sample where the features are stored in `Consul` and the `Events` in cassandra.

https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-1x/ff4j-voxxeddays-ticino-2018
