### ISSUE TITLE
please update bootstrap version

### ISSUE THREAD

**Issue by franden** [ff4j/ff4j#520]
The used bootstrap version 3.3.2 has multiple security vulnerabilities. Please update it to new Version:
 
https://github.com/ff4j/ff4j/blob/a75e93eaefa8651909d2c5e28a1211dcb2e3e9ce/ff4j-web/src/main/resources/views/view-audit.html#L7

in my case it is even not loaded
![image](https://user-images.githubusercontent.com/20822716/126757592-a468f2ff-f745-439a-8625-27aa1bdf5209.png)

**Comment by clun** [comment]
The line has been dropped from the audit view. 

Now please do not use the console in service exposed on the internet, please have a dedicated component deep in your backend. Thankss
