### ISSUE TITLE
Consul featurestore is missing in documentation

### ISSUE THREAD

**Issue by kutzi** [ff4j/ff4j#524]
I just found the consul store by chance - and it looks very promising for my use case.
Don't know if it's not supported and therefore not mentioned in docs on purpose

**Comment by kutzi** [comment]
FYI: I've created a PR for configuring the key prefix in consul: https://github.com/ff4j/ff4j/pull/525

**Comment by clun** [comment]
I added an entry but if seriously strengthen my skills on building cools docs and I am going to revamp the docs qith mkdocs
The entry
https://github.com/ff4j/ff4j/wiki/Store-Technologies#consul-io

My realization with mkdocs this year:
https://awesome-astra.github.io/

As such I will close it for now.
