### ISSUE TITLE
confirmation toggle is not working in settings

### ISSUE THREAD

**Issue by jarvis3907** [ff4j/ff4j#531]
Hello All,

   The confirmation toggle under settings in web console is automatically toggled off.

Repro steps:

      1. Go to settings in web console and enable the confirmation option.
      2. navigate to some tab and come back to settings. You will see the confirmation option is disabled 

![image](https://user-images.githubusercontent.com/54894613/139022757-91eb6fcd-253b-4a8d-b1df-0641e444e3c4.png)

**Comment by SvenStrFinlay** [comment]
Hard coding does not seem to work either. At least there is no modal. 

![Screenshot 2021-12-17 at 13 21 01](https://user-images.githubusercontent.com/82087202/146550802-13d86414-d0fb-44aa-ab29-3b2ffae89a0f.png)

**Comment by clun** [comment]
With `1.9` confirmation is enabled by default. The toggle in the Settings screen will be removed.

**Comment by clun** [comment]
<img width="1294" alt="Screenshot 2022-12-19 at 18 24 01" src="https://user-images.githubusercontent.com/726536/208484041-f094b848-8c3c-4974-aa1f-546c0db2ffbc.png">

<img width="641" alt="Screenshot 2022-12-19 at 18 23 51" src="https://user-images.githubusercontent.com/726536/208484046-7644a141-92ac-4c12-809b-ae6f8f0411a6.png">
