### ISSUE TITLE
ff4j for Spring Core and Spring Web

### ISSUE THREAD

**Issue by abhisheksurve45** [ff4j/ff4j#546]
Hi Team, 

I've seen examples in https://github.com/ff4j/ff4j-samples for configuring ff4j with spring boot 2.x, was wondering if you have any example handly with spring core / web. I've such application running on tomcat web server and want to implement ff4j.

Thanks.

**Comment by clun** [comment]
Unfortunately not all samples are available in ff4j-samples.
