### ISSUE TITLE
web api to enable the flags with strategies

### ISSUE THREAD

**Issue by mageshbabu-spg** [ff4j/ff4j#547]
Hi,

Is there any way to enable/disable the flags with strategies using web API
eg : Turn on the flag 01/01/2022 00:00:00 and Turn off at 02/01/2022 00:00:00

If possible then can you share the web API details

**Comment by mageshbabu-spg** [comment]
> office hours strategy

office hours strategy not working for me..
Can you share the sample how we need to configure in UI

**Comment by clun** [comment]
To learn about the API I would recommand to run the sample locally and use swagger.

`Is there any way to enable/disable the flags with strategies using web API`. 

> Yes. 
> <img width="1450" alt="Screenshot 2022-12-19 at 18 12 31" src="https://user-images.githubusercontent.com/726536/208481805-8a964af2-fbbd-45b2-b5d7-57e2a1465cec.png">

`Turn on the flag 01/01/2022 00:00:00 and Turn off at 02/01/2022 00:00:00`

> There is no need for the Web API for this use case. You can use a custom Flipping Strategy.
> ```java
> public class OfficeHoursFlippingStrategy extends AbstractFlipStrategy {
> 
>  /** Start Hour. */ 
>  private int start = 0;
>  
>  /** Hend Hour. */
>  private int end = 0;
> 
>  @Override
>  public void init(String featureName, Map<String, String> initValue) { 
>   super.init(featureName, initValue);
>  assertRequiredParameter("startDate");
>   assertRequiredParameter("endDate");
>   start = new Integer(initValue.get("startDate")); 
>   end = new Integer(initValue.get("endDate"));
> }
> @Override
> public boolean evaluate(String fName, FeatureStore fStore, FlippingExecutionContext ctx) { 
>   int currentHour = Calendar.getInstance().get(Calendar.HOUR_OF_DAY);
>   return (currentHour >= start && currentHour < end);
> }
> }
> ```
> Then you add the Strategy to the feature you like
> ```xml
> <?xml version="1.0" encoding="UTF-8" ?>
> <features>
> <feature uid="sayHello" enable="true" description="some desc">
>  <flipstrategy class="org.ff4j.sample.strategy.OfficeHoursFlippingStrategy" > 
 > <param name="startDate">9</param>
>  <param name="endDate">18</param>
>  </flipstrategy>
> </feature>
> </features>
> ```
> More info [HERE](https://github.com/ff4j/ff4j/wiki/Flipping-Strategies#implement-your-own-strategy)
