### ISSUE TITLE
Swagger not working for ff4j operations

### ISSUE THREAD

**Issue by pramodtalekar** [ff4j/ff4j#622]
Hello, I can see Swagger working for my controller operations but don't see the default operations mentioned on ff4j.org appearing in Swagger. I'm currently using JDK 17 and had the same issue for JDK 8/11 also.

**Comment by clun** [comment]
To have the ff4j operation in your swagger you probably need to add the proper package in the Swagger configuration bean in order for them to be scanned.

```java
 @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
            .select()
            .apis(RequestHandlerSelectors.basePackage("org.ff4j"))
            .paths(PathSelectors.regex("/api/v1.*"))
            .build()
            .apiInfo(apiInfo())
            .useDefaultResponseMessages(false);
    }
```


Here is a full fledge sample code https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-springboot2x 

You can launch this sample with:

```
docker run -p 8080:8080 ff4j/ff4j-sample-springboot2x:1.8.5
```

Then, you can access the [SWAGGER UI](http://localhost:8080/swagger-ui.html)
