### ISSUE TITLE
Update ff4j-web to use jakarta.servlet for Spring Boot 3

### ISSUE THREAD

**Issue by chrc** [ff4j/ff4j#666]
Update ff4j-web to use jakarta.servlet for Spring Boot 3

**Comment by clun** [comment]
Thank you for the issue. 

Can you please move/recreate this issue to the `spring-boot-starter` project ( can do it but you will not be notified).  This evolution is in progress, it would probably lead to a dedicated `ff4j-web` for Spring and the starter,

**Comment by chrc** [comment]
Yes! Here : https://github.com/ff4j/ff4j-spring-boot-starter-parent/issues/318
Thanks ;-)

**Comment by paul58914080** [comment]
@chrc we will close this issue and continue use track at https://github.com/ff4j/ff4j-spring-boot-starter-parent/issues/318 as ff4j-web now uses Jakarta servlet.
