### ISSUE TITLE
prototype pollution, possible XSS with ff4j 1v.9

### ISSUE THREAD

**Issue by vraravam** [ff4j/ff4j#679]
We use OWASP dependency checker in our codebase where we have ff4j as a dependency.
With the latest dependency checker v7.4.4, we have been seeing this issue:
```
ff4j-web-1.9.jar: jquery.dataTables.min.js (pkg:javascript/jquery.datatables@1.10.22) : prototype pollution, possible XSS
```
Can you please recommend how/when this can be solved?
Update: I found the suppression.xml entry in the report - but, it would be good to have a proper fix for this. TIA

**Comment by sayeedhussain** [comment]
Apparently upgrading to dataTables@1.10.23 or higher fixes at least the prototype pollution issue. Reference https://security.snyk.io/package/npm/datatables.net/1.10.22

**Comment by clun** [comment]
Thank you for reporting this. We will operate the update of dataTabes this week

**Comment by clun** [comment]
dataTables is updated to latest version in 2.0.0.
