### ISSUE TITLE
ff4j_audit table column size issue

### ISSUE THREAD

**Issue by snigdhasjg** [ff4j/ff4j#683]
Issue #238 has been fixed on version `1.7`, the same change has not been propagated to newer version.

#### Recap:
ff4j_audit has the following, and the insert/update features fails if the feature name length> 30.
```sql
"EVT_NAME" VARCHAR(30) NOT NULL
```

As a workaround we have written a migration script to alter column size for now. We would like to have it in the library itself, because ff4j is controlling table creation, it may not be sustainable  .

Thoughts?

**Comment by clun** [comment]
fixed in 2.0.0
