### ISSUE TITLE
ff4j-web bug with CSRF tags on Thymeleaf forms

### ISSUE THREAD

**Issue by vandykej17** [ff4j/ff4j#687]
**Describe the bug**
This is kind of a bug, but also a feature. We are seeing the thymeleaf tag engine is not doing normal "spring things" like CSRF tags. I tracked this down to the FF4J servlet explicitly calling out to use the `TemplateEngine` instead of `SpringTemplateEngine`. I understand not everyone using this package is using spring, so this is a feeler on how we can make this work for both Spring users and non-Spring users.

https://github.com/ff4j/ff4j/blob/main/ff4j-web/src/main/java/org/ff4j/web/FF4jServlet.java#L180

**To Reproduce**
There isn't much to reproduce it, just running the app on spring, will not use the normal `SpringTemplateEngine`. There really aren't any errors with this approach, except for very specific spring tags like adding CSRF tags or whatever else it might do.

**Expected behavior**
I was expecting the hidden CSRF tags to show up on spring forms.

**Comment by clun** [comment]
You are correct, the FF4j Servlet is using the TemplateEngine to be embedded in any Quarkus, Spring, Micronaut or even jersey applications. We have no intention to change this. If you want to apply the `SpringTemplateEngine` you can create your own servlet  as a bean and injecting... ff4j, template engine and more.

**Comment by vandykej17** [comment]
That makes sense for `ff4j-web`. Maybe I need to open this up against the `ff4j-spring-boot-starter-parent` since using that comes with an expectation that we'd be using spring boot standards like the correct template. Since it seems you are involved in that too, maybe you could save me the trouble, and tell me now, if I'll receive the same denial over in that repo.
