### ISSUE TITLE
[Bug] Using a pooling data source (example PoolingDataSourceImpl) with audit enabled, after you create a property you cannot update it

### ISSUE THREAD

**Issue by EmanuelNeculaiDev** [ff4j/ff4j#710]
**Describe the bug**
Using a pooling data source (example PoolingDataSourceImpl) with audit enabled, after you create a property you cannot update it

**To Reproduce**
1.Start ff4j dashboard in a spring environment with an Oracle DB
2.Create a property
3.Update it
4.See error ( like "{Property} already exist in store, duplicate 'name'"

**Expected behavior**
The property should be updated

**Screenshots**

![Edit_created_property](https://github.com/ff4j/ff4j/assets/126280469/adba4137-1e16-461b-87f5-6482f427e826)
![Edit_property_error](https://github.com/ff4j/ff4j/assets/126280469/11571acf-775f-42c3-9edf-e1bfbd01ca9b)

Technical problem: 
The problem is a technical one, the update is doing delete and after that insert in property table.
1.Delete is running in a connection(and session) retrieved from the pool, but is not commited(some connections from the pool might have auto-commited on, some not, it depends on the last usage of the connection)
2.Create is running in a connection(and session) retrieved from the pool. The create functionality at some point checks that the property does not exist in DB.
3.The check(select) is done again in a coneection(and session) retrieved from the pool. Now comes the problem, since the delete session(and implicit transaction) was not commited and the session opened by the check method does not see the delete happend at first step

Solution : create, delelete,update would be transactional which is not the case right now.
Btw, the feature store is implemented correctly, using transactions(meaning no auto-commit at all)

**Comment by clun** [comment]
I saw your pull request. Mergin in progress.
