### ISSUE TITLE
Ff4j client with spring boot 3.x

### ISSUE THREAD

**Issue by allantl** [ff4j/ff4j#713]
Any chance of using `ff4j-webapi-jersey2x` (or is there any alternative java client?) with spring boot 3.x? Im getting
```
java.lang.LinkageError: ClassCastException: attempting to castjar: javax.ws.rs-api
```

It seems this is due to incompatibility of 
`org.glassfish.jersey.core:jersey-client`. Spring boot 3.x is using version 3.1.1, version 1.9 seems to expect version 2.x.

**Comment by zeitan** [comment]
Same issue in my case
````
java.lang.LinkageError: ClassCastException: 
````

when try to create the ClientBuilder

**Comment by zeitan** [comment]
WIP: I'm using spring webclient to connect for now to the FF4j REST API

**Comment by paul58914080** [comment]
> Any chance of using ff4j-webapi-jersey2x (or is there any alternative java client?) with spring boot 3.x? Im getting

Have you tried [ff4j-spring-boot-starter-webmvc](https://github.com/ff4j/ff4j/issues/713#ff4j-spring-boot-starter-webmvc)? The recent release has spring-boot 3x

**Comment by zeitan** [comment]
@paul58914080 
For the server side I used [ff4j-spring-boot-starter-webmvc](https://github.com/ff4j/ff4j-spring-boot-starter-parent#ff4j-spring-boot-starter-webmvc) 
````
		<!-- FF4J -->
		<dependency>
			<groupId>org.ff4j</groupId>
			<artifactId>ff4j-spring-boot-starter-webmvc</artifactId>
			<version>${ff4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.ff4j</groupId>
			<artifactId>ff4j-web</artifactId>
			<version>${ff4j.version}</version>
		</dependency>
````
should be used too for the client side -API consuming the ff4J API/service-?

**Comment by paul58914080** [comment]
@zeitan ,

The starter `ff4j-spring-boot-starter-webmvc` already comes with `ff4j-web` i.e. you don't have to again specify `ff4j-web`. You could simplify the dependency with :

```xml
<dependency>
  <groupId>org.ff4j</groupId>
  <artifactId>ff4j-spring-boot-starter-webmvc</artifactId>
  <version>2.0.0</version>
</dependency>
```

> should be used too for the client side -API consuming the ff4J API/service-?

It depends on how you have configured the client. If you are looking for the RESTful api's then yes you can use `ff4j-spring-boot-starter-webmvc`

**Comment by Meenadaggu4121** [comment]
Ff4j-webapi-jersey2x is still on 1.9 version and what would be the compatible version for springboot3.x

**Comment by paul58914080** [comment]
> @paul58914080
> 
> Ff4j-webapi-jersey2x is still on 1.9 version and what would be the compatible version for springboot3.x.
> 
> couldn’t find any jersey2 artifacts under ff4j-spring-boot-starter-webmvc .

@Meenadaggu4121 , `ff4j-spring-boot-starter-webmvc` is purely based on spring-boot-starter-web. It does not use jersey2 dependency.

Why do you need jersey2 in ff4j-spring-boot-starter-webmvc ?

**Comment by paul58914080** [comment]
I am closing this issue as this has been mostly answered. If you have any further clarification in the same context please feel free to re-open.

**Comment by Abhishek-503** [comment]
@paul58914080 I have below method for creating bean of ff4j which call another api of ff4j service. After the sprinboot upgrade it is giving me the Linkage Error issue with ClassCastException. I want to use the ff4j-spring-boot-starter-webmvc like you suggested. can you please tell me how I can change code below for bean to be created without any error. Also I removed the ff4j-webapi-jersey2x dependency which I was using earlier.
```
	@Bean
	public FF4j ff4jClient() {
		FF4j ff4jClient = new FF4j();
		if (configurableEnvironment.acceptsProfiles(Profiles.of("aws")) || !featureFlagIsInMemoryServer) {
			//TODO: To be fixed as ff4j-webapi-jersey2x dependency causing ClassCastException after Java17 & Springboot Upgrade.
			ff4jClient.setFeatureStore(new FeatureStoreHttp(featureFlagApiUrl + "/ff4j", featureFlagAdminApiKey));
			ff4jClient.setPropertiesStore(new PropertyStoreHttp(featureFlagApiUrl + "/ff4j", featureFlagAdminApiKey));
		} else {
			ff4jClient.setFeatureStore(new InMemoryFeatureStore());
			ff4jClient.setPropertiesStore(new InMemoryPropertyStore());
		}

		populateFeatureFlags(ff4jClient, false);

		return ff4jClient;
	}
```
