### ISSUE TITLE
Notification of toggle activation/decativation over communication channels

### ISSUE THREAD

**Issue by c-n-c** [ff4j/ff4j#714]
**Is your feature request related to a problem? Please describe.**
Currently ff4j logs the feature changes, at INFO level, the same can be proactively used to send alerts / notfication to the configured consumers

**Describe the solution you'd like**
In the era of cloud AWS SNS or Incoming Webhooks can be integration point to alert / notify the toggle consumers, and improve development efficacy

**Describe alternatives you've considered**
Alternative can be to trap the database change triggers and integrate notification after the toggle changes are presisted successfully 

**Additional context**
I was able to create a small  app that does this data reporting for now

<img width="1486" alt="image" src="https://github.com/ff4j/ff4j/assets/1103228/b7085258-37f8-4a7c-a6e7-52a9880c6431">

here are two such implementation highlighted.

**Comment by vraravam** [comment]
The notifications can be pluggable with different implementations (equivalent of SNS in different managed services by the different cloud providers)

**Comment by clun** [comment]
It is a good idea. The hooks can be implemented in the eventRepository.

Here some code i proposed in previous issue
https://github.com/ff4j/ff4j/issues/442

I would be happy to merge a PR, maybe defining destination systems for such notification. 

On V3 it is included but very far from ready, I have my regular job and a side job now...very hard to give back some time for a major version.
https://github.com/ff4j/ff4j/blob/v3/ff4j-core/src/main/java/org/ff4j/backend/BackendRepositoryListener.java
