### ISSUE TITLE
[Bug] org.ff4j » ff4j-spring-boot-starter 2.0.0 is not available in maven central

### ISSUE THREAD

**Issue by emecas** [ff4j/ff4j#715]
**Describe the bug**

Last version available currently is 1.9 Dec 20, 2022, even 2.0.0 was released Feb 7, 2023

[maven central](https://mvnrepository.com/artifact/org.ff4j/ff4j-spring-boot-starter)

**Screenshots**

![image](https://github.com/ff4j/ff4j/assets/849502/793a5485-5976-4ac7-a505-c4f83cfe5218)

**Additional context**

https://github.com/ff4j/ff4j/releases/tag/2.0.0

**Comment by BlueLeer** [comment]
我已收到  谢谢 我会尽快查看

**Comment by paul58914080** [comment]
@emecas , 

The spring boot starter project has been moved to https://github.com/ff4j/ff4j-spring-boot-starter-parent (quite a while back). The issue also needs to be there.

However, please check the release notes https://github.com/ff4j/ff4j-spring-boot-starter-parent/releases/tag/2.0.0

>
> Instead of one starter i.e. ff4j-spring-boot-starter to pave way for reactive programming we have now two starters
>  - ff4j-spring-boot-starter-webmvc is more stable and can be used in production.
>  - ff4j-spring-boot-starter-webflux is more beta as we are still working to make it more reactive i.e. store, console etc 

Hope this answers your question. 

I am closing this issue, in case you have any further questions pertaining to the starter please raise it at https://github.com/ff4j/ff4j-spring-boot-starter-parent/issues

Happy Coding !
