### ISSUE TITLE
How can I customize the ui of web console including logo and header ?

### ISSUE THREAD

**Issue by sahassakhare** [ff4j/ff4j#716]
How can I customize the ui of web console including logo and header ?

**Comment by clun** [comment]
Hello,

The framework it self does not offer such customization but you can do is exclude `ff4j-web` package from you build and provide you own.

The files you would have to edit are then simply;
- https://github.com/ff4j/ff4j/blob/main/ff4j-web/src/main/resources/ff4j-template.html
- https://github.com/ff4j/ff4j/tree/main/ff4j-web/src/main/resources/views
